// engineering/codebase/wheelhouse.frontend-services/src/presentation/products/components/ProductsPanel.tsx
import { Fragment, useState, type ReactNode } from 'react';
import { Eye, Package, Pencil, Trash2 } from 'lucide-react';
import { Button } from '@wow-two-beta/ui/presentation/actions';
import { Code, Table, TableBody, TableCell, TableHead, TableHeaderCell, TableRow, Text } from '@wow-two-beta/ui/presentation/display';
import { StatusIndicator } from '@wow-two-beta/ui/presentation/feedback';
import { useProducts } from '@/application/products';
import { ProductStatus, type Product } from '@/domain/products';
import { Expand, LoadState, Panel, TableStyles, useExpand } from '@/presentation/common/components';
import { Skeleton } from '@/presentation/common/skeleton';
import { RegisterProductForm } from './RegisterProductForm';

const STATUS_TONE: Record<ProductStatus, 'neutral' | 'success' | 'warning' | 'destructive'> = {
  Active: 'success',
  Paused: 'warning',
  Killed: 'destructive',
  Draft: 'neutral',
};

const COLUMNS = 5;

// The first load's stand-in rows, in the loaded table's shape.
const PLACEHOLDER: Product[] = [1, 2, 3].map((index) => ({
  id: `placeholder-${index}`, slug: 'product-slug', name: 'Product name', repo: 'owner/repository',
  status: ProductStatus.Active, createdAtUtc: '2026-01-01T00:00:00Z',
}));

/** Props for {@link ProductsPanel}. */
export interface ProductsPanelProps {
  /** The registration form is open; the page header's action opens it. */
  registering: boolean;
  onRegisteringChange: (registering: boolean) => void;
}

/** The Products registry — list portfolio products and create / view / edit / delete them. */
export function ProductsPanel(props: ProductsPanelProps) {
  const { products, loading, error, reload, create, update, remove } = useProducts();
  const [editing, setEditing] = useState<Product | null>(null);
  const [viewing, setViewing] = useState<string | null>(null);
  const [confirmDelete, setConfirmDelete] = useState<string | null>(null);
  const [deletingId, setDeletingId] = useState<string | null>(null);

  function closeForm() {
    props.onRegisteringChange(false);
    setEditing(null);
  }

  async function onDelete(id: string) {
    setDeletingId(id);
    try {
      await remove(id);
      setConfirmDelete(null);
      if (viewing === id) setViewing(null);
    } finally {
      setDeletingId(null);
    }
  }

  return (
    <Panel title="Registry" description="Each product's slug, source repository and lifecycle status.">
      <div className="flex flex-col gap-5">
        <Expand open={props.registering || editing !== null} className="-mb-5">
          <div className="pb-5">
            <RegisterProductForm key={editing?.id ?? 'create'} product={editing ?? undefined} create={create}
              update={update} onSaved={closeForm} onCancel={closeForm} />
          </div>
        </Expand>
        <LoadState loading={loading} error={error ? { message: error } : null} empty={products.length === 0}
          emptyIcon={<Package size={28} />} emptyTitle="No products yet"
          emptyDescription="Register your first portfolio product to start deploying."
          emptyActions={props.registering ? undefined : (
            <Button variant="solid" tone="primary" size="sm" onClick={() => props.onRegisteringChange(true)}>
              Register product
            </Button>
          )}
          onRetry={() => void reload()}
          skeleton={
            <Skeleton.Group loading label="Loading products">
              <ProductsTable products={PLACEHOLDER} />
            </Skeleton.Group>
          }>
          <ProductsTable products={products}
            actions={(product) => (
              <div className="flex items-center justify-end gap-1">
                <Button variant="ghost" tone="neutral" size="sm" aria-label={`View ${product.name}`} leadingSlot={<Eye size={15} />}
                  onClick={() => setViewing((current) => (current === product.id ? null : product.id))} />
                <Button variant="ghost" tone="neutral" size="sm" aria-label={`Edit ${product.name}`} leadingSlot={<Pencil size={15} />}
                  onClick={() => {
                    props.onRegisteringChange(false);
                    setEditing(product);
                  }} />
                <Button variant="ghost" tone="danger" size="sm" aria-label={`Delete ${product.name}`} leadingSlot={<Trash2 size={15} />}
                  onClick={() => setConfirmDelete(product.id)} />
              </div>
            )}
            details={(product) => (
              <>
                <DetailRow open={viewing === product.id} className="bg-muted/40">
                  <dl className="grid grid-cols-2 gap-x-6 gap-y-2 px-3 py-4 text-xs sm:grid-cols-4">
                    <Detail label="Id"><Code className="break-all">{product.id}</Code></Detail>
                    <Detail label="Repo"><Code className="break-all">{product.repo}</Code></Detail>
                    <Detail label="Status">{product.status}</Detail>
                    <Detail label="Created">{new Date(product.createdAtUtc).toLocaleString()}</Detail>
                  </dl>
                </DetailRow>
                <DetailRow open={confirmDelete === product.id} className="bg-destructive-soft">
                  <div className="flex items-center justify-between gap-4 px-3 py-3">
                    <Text size="sm">Delete <span className="font-medium">{product.name}</span>? This cannot be undone.</Text>
                    <div className="flex items-center gap-2">
                      <Button variant="ghost" tone="neutral" size="sm" onClick={() => setConfirmDelete(null)}>Cancel</Button>
                      <Button variant="solid" tone="danger" size="sm" isLoading={deletingId === product.id}
                        onClick={() => void onDelete(product.id)}>
                        Delete
                      </Button>
                    </div>
                  </div>
                </DetailRow>
              </>
            )} />
        </LoadState>
      </div>
    </Panel>
  );
}

// ---- Table ----

function ProductsTable(props: {
  products: Product[];
  actions?: (product: Product) => ReactNode;
  /** Rows under a product: its details or the delete confirmation. */
  details?: (product: Product) => ReactNode;
}) {
  return (
    <Table density="compact" isHoverable className="table-fixed" containerClassName={TableStyles.scrollBox}>
      {/* Fixed columns: an opening detail row never re-lays the header. */}
      <colgroup>
        <col className="w-[22%]" />
        <col className="w-[18%]" />
        <col />
        <col className="w-32" />
        <col className="w-32" />
      </colgroup>
      <TableHead className={TableStyles.stickyHead}>
        <TableRow>
          <TableHeaderCell>Name</TableHeaderCell><TableHeaderCell>Slug</TableHeaderCell>
          <TableHeaderCell>Repo</TableHeaderCell><TableHeaderCell>Status</TableHeaderCell>
          <TableHeaderCell><span className="sr-only">Actions</span></TableHeaderCell>
        </TableRow>
      </TableHead>
      <TableBody>
        {props.products.map((product) => (
          <Fragment key={product.id}>
            <TableRow>
              <TableCell className="truncate font-medium"><Skeleton.Slot>{product.name}</Skeleton.Slot></TableCell>
              <TableCell className="truncate font-mono text-xs text-muted-foreground"><Skeleton.Slot>{product.slug}</Skeleton.Slot></TableCell>
              <TableCell className="truncate font-mono text-xs text-muted-foreground"><Skeleton.Slot>{product.repo}</Skeleton.Slot></TableCell>
              <TableCell>
                <Skeleton.Slot><StatusIndicator tone={STATUS_TONE[product.status]} label={product.status} /></Skeleton.Slot>
              </TableCell>
              <TableCell>{props.actions?.(product)}</TableCell>
            </TableRow>
            {props.details?.(product)}
          </Fragment>
        ))}
      </TableBody>
    </Table>
  );
}

// A row under a product that opens and closes by height; it leaves no empty row behind once closed.
function DetailRow(props: { open: boolean; className: string; children: ReactNode }) {
  const expand = useExpand(props.open);
  if (!expand.mounted) return null;
  return (
    <TableRow className={props.className}>
      <TableCell colSpan={COLUMNS} className="p-0">
        <div {...expand.region}>
          <div className="min-h-0 overflow-hidden">{props.children}</div>
        </div>
      </TableCell>
    </TableRow>
  );
}

function Detail(props: { label: string; children: ReactNode }) {
  return (
    <div className="flex flex-col gap-1">
      <dt className="font-medium uppercase tracking-wide text-muted-foreground">{props.label}</dt>
      <dd className="text-foreground">{props.children}</dd>
    </div>
  );
}

// engineering/codebase/wheelhouse.frontend-services/apps/web/src/presentation/products/components/ProductsPanel.vue
<script lang="ts">
/** The registration action is owned by the route toolbar. */
export interface ProductsPanelProps {
  readonly registering: boolean;
}
</script>

<script setup lang="ts">
import { computed, ref, watch } from "vue";
import {
  ChevronRight,
  Info,
  Package,
  Pencil,
  Search,
  Trash2,
} from "lucide-vue-next";
import { Button, CopyButton } from "@wow-two-beta/ui-vue/presentation/actions";
import { Badge } from "@wow-two-beta/ui-vue/presentation/display";
import {
  Alert,
  SkeletonState,
} from "@wow-two-beta/ui-vue/presentation/feedback";
import { SearchInput } from "@wow-two-beta/ui-vue/presentation/forms";
import {
  Modal,
  ModalContent,
  ModalHeader,
  ModalTitle,
  ModalDescription,
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "@wow-two-beta/ui-vue/presentation/overlays";
import { useProducts } from "@/application/products";
import { ProductStatus, type Product } from "@/domain/products";
import { WorkspaceProductBindings } from "@/application/workspace/WorkspaceInventory";
import RegisterProductForm from "./RegisterProductForm.vue";
import RepositoryActions from "./RepositoryActions.vue";
import ProductIcon from "./ProductIcon.vue";

/** Presents portfolio selection with a contextual inspector and confirmed registry changes. */
defineOptions({ name: "ProductsPanel" });
const props = defineProps<ProductsPanelProps>();
const emit = defineEmits<{ "update:registering": [value: boolean] }>();

const statusVariant = {
  [ProductStatus.Active]: "success",
  [ProductStatus.Paused]: "warning",
  [ProductStatus.Killed]: "danger",
  [ProductStatus.Draft]: "neutral",
} as const;
const { products, loading, error, reload, create, update, remove } =
  useProducts();
const search = ref("");
const selectedId = ref<string | null>(null);
const editing = ref<Product | null>(null);
const confirmingDelete = ref(false);
const deleting = ref(false);
const deleteError = ref<string | null>(null);
const formPending = ref(false);
const visibleProducts = computed(() => {
  const term = search.value.trim().toLocaleLowerCase();
  return products.value.filter((product) =>
    `${product.name} ${product.slug} ${product.repo}`
      .toLocaleLowerCase()
      .includes(term),
  );
});
const selected = computed(
  () =>
    visibleProducts.value.find((product) => product.id === selectedId.value) ??
    null,
);
const formOpen = computed(() => props.registering || editing.value !== null);
/** The runner catalog product a registry entry is bound to, which lists its branches and commits. */
const runnerProduct = computed(
  () =>
    WorkspaceProductBindings.find(
      (binding) =>
        binding.registrySlug === selected.value?.slug &&
        binding.repository === selected.value?.repo,
    )?.runnerProduct ?? null,
);

/** Keeps the inspector attached to a visible product after searches or registry changes. */
watch(
  visibleProducts,
  (items) => {
    if (!items.some((item) => item.id === selectedId.value))
      selectedId.value = items[0]?.id ?? null;
  },
  { immediate: true },
);
/** Clears a stale deletion confirmation when the inspected product changes. */
watch(selectedId, () => {
  confirmingDelete.value = false;
  deleteError.value = null;
});
/** Switches registration into its own editor instance. */
watch(
  () => props.registering,
  (open) => {
    if (open) editing.value = null;
  },
);

/** Closes a settled form without dismissing a pending server write. */
function closeForm(): void {
  if (formPending.value) return;
  editing.value = null;
  emit("update:registering", false);
}

/** Starts editing the selected registry item. */
function editProduct(product: Product): void {
  emit("update:registering", false);
  editing.value = product;
}

/** Removes only the explicitly confirmed product after the server accepts the deletion. */
async function deleteProduct(): Promise<void> {
  if (!selected.value || deleting.value) return;
  const id = selected.value.id;
  deleting.value = true;
  deleteError.value = null;
  try {
    const result = await remove(id);
    if (result.ok) confirmingDelete.value = false;
    else deleteError.value = result.failure.message;
  } finally {
    deleting.value = false;
  }
}

/** Finishes the form after its submission lifecycle has settled. */
function saved(): void {
  formPending.value = false;
  closeForm();
}
</script>

<template>
  <div
    class="wh-glass grid min-h-[26rem] overflow-hidden rounded-2xl border lg:grid-cols-[20rem_minmax(0,1fr)]"
  >
    <section
      class="wh-glass-subtle min-w-0 border-b border-border p-4 sm:p-5 lg:border-b-0 lg:border-r"
      aria-label="Product registry"
    >
      <div class="mb-4 flex items-center justify-between gap-3">
        <h2 class="text-sm font-semibold">Your products</h2>
        <p
          v-if="!loading || products.length > 0"
          class="text-sm text-muted-foreground"
        >
          {{ products.length }}
          {{ products.length === 1 ? "product" : "products" }}
        </p>
        <SkeletonState v-else class="h-4 w-36" aria-hidden="true" />
      </div>
      <SearchInput
        v-model="search"
        aria-label="Search products"
        placeholder="Find a product…"
        class="mb-4 w-full"
      />
      <div v-if="error && products.length > 0" class="mb-4 space-y-3">
        <Alert
          severity="warning"
          title="Showing the last registry snapshot"
          :description="error"
        />
        <Button size="sm" variant="outline" @click="reload"
          >Retry refresh</Button
        >
      </div>
      <div
        v-if="loading && products.length === 0"
        class="space-y-2"
        role="status"
        aria-label="Loading products"
      >
        <div
          v-for="index in 3"
          :key="index"
          class="flex items-center gap-3 rounded-xl border border-border bg-card p-3"
          aria-hidden="true"
        >
          <SkeletonState class="size-10 shrink-0 rounded-lg" />
          <div class="flex-1 space-y-2">
            <SkeletonState class="h-4 w-3/4" /><SkeletonState
              class="h-3 w-1/2"
            />
          </div>
        </div>
      </div>
      <div v-else-if="error && products.length === 0" class="space-y-3">
        <Alert
          severity="danger"
          title="Registry unavailable"
          :description="error"
        />
        <Button variant="outline" @click="reload">Retry</Button>
      </div>
      <div
        v-else-if="products.length === 0"
        class="flex min-h-52 flex-col items-center justify-center gap-3 py-6 text-center"
      >
        <div class="rounded-2xl bg-primary-soft p-4 text-primary">
          <Package :size="28" />
        </div>
        <h2 class="text-xl font-semibold">Your portfolio starts here</h2>
        <p class="max-w-sm text-sm text-muted-foreground">
          Register a product and connect its source repository.
        </p>
        <Button @click="emit('update:registering', true)"
          >Register product</Button
        >
      </div>
      <div v-else-if="visibleProducts.length === 0" class="py-8 text-center">
        <Search :size="24" class="mx-auto mb-3 text-muted-foreground" />
        <p class="font-medium">No matching products</p>
        <p class="mt-1 text-sm text-muted-foreground">
          Try a different name or repository.
        </p>
      </div>
      <div v-else class="max-h-[28rem] space-y-2 overflow-y-auto p-1 -m-1">
        <button
          v-for="product in visibleProducts"
          :key="product.id"
          type="button"
          :aria-pressed="selectedId === product.id"
          @click="selectedId = product.id"
          class="group flex w-full min-w-0 items-center gap-3 rounded-xl border p-3 text-left transition-colors focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-ring"
          :class="
            selectedId === product.id
              ? 'border-primary/40 bg-primary-soft'
              : 'border-transparent hover:border-border hover:bg-card'
          "
        >
          <ProductIcon :product-id="product.id" :name="product.name" />
          <div class="min-w-0 flex-1">
            <p class="truncate text-sm font-semibold">{{ product.name }}</p>
            <p class="mt-1 truncate text-xs text-muted-foreground">
              {{ product.slug }}
            </p>
          </div>
          <ChevronRight :size="16" class="shrink-0 text-muted-foreground" />
        </button>
      </div>
    </section>

    <section aria-label="Product details" class="min-w-0 bg-card p-5 sm:p-7">
      <template v-if="selected">
        <div
          class="flex flex-wrap items-start justify-between gap-4 border-b border-border pb-6"
        >
          <div class="min-w-0">
            <div class="mb-3 flex items-center gap-2">
              <Package :size="16" class="text-muted-foreground" />
              <span class="text-xs text-muted-foreground">Product details</span>
            </div>
            <h2 class="flex items-center gap-1 break-words text-xl font-semibold">
              <ProductIcon
                :product-id="selected.id"
                :name="selected.name"
                size="lg"
                class="mr-2"
              />
              {{ selected.name }}
              <Popover placement="bottom-start">
                <PopoverTrigger as-child>
                  <Button
                    variant="ghost"
                    tone="neutral"
                    size="sm"
                    class="px-1.5 text-muted-foreground"
                    aria-label="Registry identifiers"
                    title="Registry identifiers"
                  >
                    <Info :size="15" />
                  </Button>
                </PopoverTrigger>
                <PopoverContent class="w-80 p-3 text-xs font-normal">
                  <p class="text-muted-foreground">Product ID</p>
                  <div class="mt-1 flex items-center gap-2">
                    <code class="min-w-0 flex-1 break-all font-mono">{{
                      selected.id
                    }}</code>
                    <CopyButton
                      :text="selected.id"
                      size="sm"
                      aria-label="Copy the product ID"
                      copied-aria-label="Product ID copied"
                    />
                  </div>
                </PopoverContent>
              </Popover>
            </h2>
            <p class="mt-1 break-all font-mono text-xs text-muted-foreground">
              {{ selected.slug }}
            </p>
          </div>
          <Button variant="outline" size="sm" @click="editProduct(selected)">
            <template #leading><Pencil :size="15" /></template>Edit product
          </Button>
        </div>
        <dl class="my-6 grid gap-x-8 gap-y-6 text-sm sm:grid-cols-2">
          <div class="min-w-0 sm:col-span-2">
            <dt class="mb-2 text-xs text-muted-foreground">
              Source repository
            </dt>
            <dd>
              <RepositoryActions
                :repository="selected.repo"
                :runner-product="runnerProduct"
              />
            </dd>
          </div>
          <div>
            <dt class="mb-1 text-xs text-muted-foreground">Lifecycle</dt>
            <dd>
              <Badge :variant="statusVariant[selected.status]">{{
                selected.status
              }}</Badge>
            </dd>
          </div>
          <div>
            <dt class="mb-1 text-xs text-muted-foreground">Registered</dt>
            <dd>{{ new Date(selected.createdAtUtc).toLocaleString() }}</dd>
          </div>
        </dl>
        <div
          v-if="confirmingDelete"
          class="space-y-3 rounded-xl bg-destructive-soft p-4"
        >
          <p class="text-sm text-destructive-soft-foreground">
            Delete {{ selected.name }}? This cannot be undone.
          </p>
          <p
            v-if="deleteError"
            role="alert"
            class="text-sm text-destructive-soft-foreground"
          >
            {{ deleteError }}
          </p>
          <div class="flex gap-2">
            <Button
              size="sm"
              variant="ghost"
              tone="neutral"
              :is-disabled="deleting"
              @click="confirmingDelete = false"
              >Cancel</Button
            >
            <Button
              size="sm"
              tone="danger"
              :is-loading="deleting"
              @click="deleteProduct"
              >Delete product</Button
            >
          </div>
        </div>
        <div v-else class="border-t border-border pt-4">
          <Button
            variant="ghost"
            tone="danger"
            size="sm"
            aria-label="Delete product"
            @click="confirmingDelete = true"
          >
            <template #leading><Trash2 :size="14" /></template>Delete product
          </Button>
        </div>
      </template>
      <div
        v-else
        class="flex min-h-60 flex-col items-center justify-center gap-3 text-center text-muted-foreground"
      >
        <Package :size="24" />
        <p class="text-sm">
          {{
            search
              ? "No products match your search."
              : "Select a product to inspect its details."
          }}
        </p>
      </div>
    </section>
  </div>

  <Modal
    :open="formOpen"
    :dismiss-on-outside-click="!formPending"
    :dismiss-on-escape="!formPending"
    @update:open="
      (open) => {
        if (!open) closeForm();
      }
    "
  >
    <ModalContent class="flex max-h-[calc(100dvh-2rem)] w-[min(40rem,calc(100vw-2rem))] flex-col overflow-y-auto">
      <ModalHeader>
        <ModalTitle>{{
          editing ? "Edit product" : "Register product"
        }}</ModalTitle>
        <ModalDescription
          >Connect a portfolio product to its GitHub source
          repository.</ModalDescription
        >
      </ModalHeader>
      <RegisterProductForm
        v-if="formOpen"
        :key="editing?.id ?? 'new'"
        v-bind="editing ? { initialProduct: editing } : {}"
        :create="create"
        :update="update"
        @saved="saved"
        @cancel="closeForm"
        @pending="formPending = $event"
      />
    </ModalContent>
  </Modal>
</template>
