// engineering/codebase/wheelhouse.frontend-services/apps/web/src/bootstrap/App.vue
<script setup lang="ts">
import { RouterView } from 'vue-router';
import { Spinner } from '@wow-two-beta/ui-vue/presentation/feedback';
import { useAuth } from '@/application/auth';
import SignInScreen from '@/presentation/auth/SignInScreen.vue';
import AppLayout from './AppLayout.vue';

/** Gates every private workspace route on the operator's GitHub session. */
defineOptions({ name: 'App' });
const auth = useAuth();
</script>
<template>
  <div v-if="auth.loading.value" class="flex min-h-svh items-center justify-center bg-background">
    <Spinner label="Loading Wheelhouse" />
  </div>
  <AppLayout v-else-if="auth.user.value" :user="auth.user.value" @sign-out="auth.signOut">
    <RouterView />
  </AppLayout>
  <SignInScreen v-else :error="auth.error.value" @sign-in="auth.signIn" />
</template>

// engineering/codebase/wheelhouse.frontend-services/src/bootstrap/App.tsx
import { Navigate, Route, Routes } from 'react-router-dom';
import { Spinner } from '@wow-two-beta/ui/presentation/feedback';
import { useAuth } from '@/application/auth';
import { SignInScreen } from '@/presentation/auth';
import { AppLayout } from './AppLayout';
import { APP_ROUTES } from './routes';

/** The dashboard root, gated behind the operator's GitHub session. */
export function App() {
  const auth = useAuth();
  if (auth.loading)
    return <div className="flex min-h-full items-center justify-center"><Spinner label="Loading Wheelhouse" /></div>;
  if (!auth.user) return <SignInScreen onSignIn={auth.signIn} />;
  return (
    <AppLayout user={auth.user} onSignOut={() => void auth.signOut()}>
      <Routes>
        {APP_ROUTES.map((route) => <Route key={route.path} path={route.path} element={<route.page />} />)}
        <Route path="*" element={<Navigate to="/" replace />} />
      </Routes>
    </AppLayout>
  );
}
