// engineering/codebase/wheelhouse.frontend-services/src/presentation/deployments/pages/DeploymentsPage.vue
<script setup lang="ts">
import { RefreshCw, Rocket } from "lucide-vue-next";

import { Button } from "@wow-two-beta/ui-vue/presentation/actions";

import { useRefresh } from "@/application/common";
import { useDeploymentHistory } from "@/application/deployments";
import type { DeploymentJob } from "@/domain/deployments";
import {
  LoadState,
  PageActions,
  Panel,
} from "@/presentation/common/components";

import DeployModal from "../components/DeployModal.vue";
import DeploymentStatsPanel from "../components/DeploymentStatsPanel.vue";
import HistoryTable from "../components/HistoryTable.vue";
import HistoryTableSkeleton from "../components/HistoryTableSkeleton.vue";
import TargetsPanel from "../components/TargetsPanel.vue";
import { useDeployModal } from "../hooks/useDeployModal";

/** Renders portfolio deployment history, complete statistics and target operations. */
defineOptions({ name: "DeploymentsPage" });
const history = useDeploymentHistory();
const historyRefresh = useRefresh(history.refetch);
const deploy = useDeployModal();

/** Preselects the exact successful submission's target and bundle for a new confirmation. */
function redeploy(job: DeploymentJob): void {
  if (job.targetId && job.bundleId)
    deploy.openDeploy({ target: job.targetId, release: job.bundleId });
}
</script>

<template>
  <div class="flex flex-col gap-6">
    <PageActions>
      <Button variant="solid" tone="primary" @click="deploy.openDeploy()">
        <template #leading><Rocket :size="16" /></template>Deploy
      </Button>
    </PageActions>
    <TargetsPanel />
    <Panel
      title="Recent deployments"
      description="The latest 50 submissions across all products and environments."
    >
      <template #actions>
        <Button
          variant="ghost"
          tone="neutral"
          size="sm"
          @click="historyRefresh.refresh()"
          :is-loading="historyRefresh.refreshing.value"
        >
          <template #leading><RefreshCw :size="14" /></template>Refresh
        </Button>
      </template>
      <LoadState
        :loading="history.loading.value || historyRefresh.refreshing.value"
        :error="history.error.value"
        :has-data="Boolean(history.data.value)"
        :empty="!history.data.value?.length"
        empty-title="No deployments yet"
        @retry="historyRefresh.refresh()"
      >
        <template #skeleton><HistoryTableSkeleton /></template>
        <HistoryTable
          :jobs="history.data.value ?? []"
          :on-redeploy="redeploy"
        />
      </LoadState>
    </Panel>
    <DeploymentStatsPanel show-targets />
    <DeployModal
      :key="deploy.session.value"
      :open="deploy.open.value"
      :selection="deploy.selection.value"
      @update:open="deploy.onOpenChange"
    />
  </div>
</template>

// engineering/codebase/wheelhouse.frontend-services/src/presentation/deployments/pages/DeploymentsPage.tsx
import { RefreshCw, Rocket } from 'lucide-react';
import { Button } from '@wow-two-beta/ui/presentation/actions';
import { useDeploymentHistory } from '@/application/deployments';
import { LoadState, PageActions, Panel } from '@/presentation/common/components';
import { DeployModal } from '../components/DeployModal';
import { DeploymentStatsPanel } from '../components/DeploymentStatsPanel';
import { HistoryTable, HistoryTableSkeleton } from '../components/HistoryTable';
import { TargetsPanel } from '../components/TargetsPanel';
import { useDeployModal } from '../hooks/useDeployModal';

/** Deploy, observe and recover releases across the code-owned targets. */
export function DeploymentsPage() {
  const history = useDeploymentHistory();
  const deploy = useDeployModal();
  return (
    <div className="flex flex-col gap-6">
      <PageActions>
        <Button variant="solid" tone="primary" leadingSlot={<Rocket size={16} />} onClick={() => deploy.openDeploy()}>
          Deploy
        </Button>
      </PageActions>
      <TargetsPanel />
      <DeploymentStatsPanel showTargets />
      <Panel title="History" description="Recent deployments with the reason any of them stopped."
        actions={<Button variant="ghost" tone="neutral" size="sm" leadingSlot={<RefreshCw size={14} />}
          onClick={() => void history.refetch()}>Refresh</Button>}>
        <LoadState loading={history.loading} error={history.error} empty={!history.data?.length}
          emptyTitle="No deployments yet" onRetry={() => void history.refetch()} skeleton={<HistoryTableSkeleton />}>
          <HistoryTable jobs={history.data ?? []}
            onRedeploy={(job) => deploy.openDeploy({ target: job.targetId ?? '', release: job.bundleId ?? '' })} />
        </LoadState>
      </Panel>
      <DeployModal key={deploy.session} open={deploy.open} onOpenChange={deploy.onOpenChange} selection={deploy.selection} />
    </div>
  );
}
