// engineering/codebase/wheelhouse.frontend-services/src/presentation/auth/SignInScreen.tsx
import { Github } from 'lucide-react';
import { Button } from '@wow-two-beta/ui/presentation/actions';
import { Card, Heading, Text } from '@wow-two-beta/ui/presentation/display';

/** Props for {@link SignInScreen}. */
export interface SignInScreenProps {
  onSignIn: () => void;
}

/** The private sign-in gate for the authorized GitHub operator. */
export function SignInScreen(props: SignInScreenProps) {
  return (
    <div className="flex min-h-full items-center justify-center bg-background px-6 py-16 text-foreground">
      <Card className="w-full max-w-sm border border-border p-8">
        <div className="flex flex-col items-center gap-6 text-center">
          <div>
            <Heading level={1} size="lg">Wheelhouse</Heading>
            <Text color="muted" size="sm">Infrastructure control plane</Text>
          </div>
          <Text color="muted" size="sm">This control plane is private. Sign in with the authorized GitHub account.</Text>
          <Button variant="solid" tone="primary" size="lg" isFullWidth leadingSlot={<Github size={18} />} onClick={props.onSignIn}>
            Sign in with GitHub
          </Button>
        </div>
      </Card>
    </div>
  );
}

// engineering/codebase/wheelhouse.frontend-services/apps/web/src/presentation/auth/SignInScreen.vue
<script lang="ts">
/** Optional failure from resolving or clearing the private session. */
export interface SignInScreenProps {
  readonly error?: { readonly message: string } | null;
}
</script>

<script setup lang="ts">
import { Github } from "lucide-vue-next";
import { Button } from "@wow-two-beta/ui-vue/presentation/actions";
import { Card } from "@wow-two-beta/ui-vue/presentation/display";
import { Alert } from "@wow-two-beta/ui-vue/presentation/feedback";
import { BrandWordmark } from "@/presentation/shell";

/** Renders the private operator sign-in gate. */
defineOptions({ name: "SignInScreen" });
const props = defineProps<SignInScreenProps>();
const emit = defineEmits<{ "sign-in": [] }>();
</script>

<template>
  <main
    class="flex min-h-dvh items-center justify-center bg-background px-5 py-16 text-foreground"
  >
    <Card
      class="flex w-full max-w-sm flex-col items-center rounded-[2rem] border border-border p-9 text-center"
    >
      <h1><BrandWordmark :height="40" /></h1>
      <p class="mt-2 text-sm text-muted-foreground">
        Private operations console
      </p>
      <Alert
        v-if="props.error"
        class="mt-6 w-full text-left"
        severity="danger"
        title="Session unavailable"
        :description="props.error.message"
      />
      <Button class="mt-8" size="lg" is-full-width @click="emit('sign-in')">
        <template #leading><Github :size="18" /></template>Sign in with GitHub
      </Button>
    </Card>
  </main>
</template>
