// engineering/codebase/drydock.frontend-services/src/components/SignInScreen.tsx
import { Github } from 'lucide-react';
import { Button } from '@wow-two-beta/ui/presentation/actions';
import { Card, Heading, Text } from '@wow-two-beta/ui/presentation/display';

interface SignInScreenProps {
  onSignIn: () => void;
}

/** Pre-auth gate — the single admin signs in with GitHub to reach the dashboard. */
export function SignInScreen({ onSignIn }: SignInScreenProps) {
  return (
    <div className="flex min-h-full items-center justify-center bg-background px-6 py-16 text-foreground">
      <Card className="w-full max-w-sm border border-border p-8">
        <div className="flex flex-col items-center gap-6 text-center">
          <div>
            <Heading level={1} size="lg">
              Drydock
            </Heading>
            <Text color="muted" size="sm">
              Product ops &amp; deploy control plane
            </Text>
          </div>

          <Text color="muted" size="sm">
            This control plane is private. Sign in with the authorized GitHub account to continue.
          </Text>

          <Button
            variant="solid"
            tone="primary"
            size="lg"
            isFullWidth
            leadingSlot={<Github size={18} />}
            onClick={onSignIn}
          >
            Sign in with GitHub
          </Button>
        </div>
      </Card>
    </div>
  );
}

// engineering/codebase/wheelhouse.frontend-services/src/presentation/auth/SignInScreen.vue
<script lang="ts">
/** Optional failure from resolving or clearing the private session. */
export interface SignInScreenProps {
  readonly error?: { readonly message: string } | null;
}
</script>

<script setup lang="ts">
import { Github, Ship } from "lucide-vue-next";
import { Button } from "@wow-two-beta/ui-vue/presentation/actions";
import { Card } from "@wow-two-beta/ui-vue/presentation/display";
import { Alert } from "@wow-two-beta/ui-vue/presentation/feedback";

/** Renders the private operator sign-in gate. */
defineOptions({ name: "SignInScreen" });
const props = defineProps<SignInScreenProps>();
const emit = defineEmits<{ "sign-in": [] }>();
</script>

<template>
  <main
    class="flex min-h-dvh items-center justify-center bg-background px-5 py-16 text-foreground"
  >
    <Card class="w-full max-w-md rounded-[2rem] border border-border p-9">
      <div
        class="mb-8 flex size-14 items-center justify-center rounded-2xl bg-primary text-primary-foreground"
      >
        <Ship :size="27" />
      </div>
      <p
        class="mb-2 text-xs font-medium uppercase tracking-[0.2em] text-muted-foreground"
      >
        Your operations workspace
      </p>
      <h1 class="text-3xl font-semibold tracking-tight">Wheelhouse</h1>
      <p class="mb-8 mt-4 text-sm leading-6 text-muted-foreground">
        Products, deployments, and infrastructure in one place. Sign in with
        your authorized GitHub account.
      </p>
      <Alert
        v-if="props.error"
        class="mb-5"
        severity="danger"
        title="Session unavailable"
        :description="props.error.message"
      />
      <Button size="lg" is-full-width @click="emit('sign-in')">
        <template #leading><Github :size="18" /></template>Sign in with GitHub
      </Button>
      <p class="mt-5 text-center text-xs text-muted-foreground">
        Private control plane · Authorized operators only
      </p>
    </Card>
  </main>
</template>
