// engineering/codebase/wheelhouse.frontend-services/src/presentation/secrets/components/NamespaceModal.tsx
import { useState, type FormEvent } from 'react';
import { Button } from '@wow-two-beta/ui/presentation/actions';
import { Alert } from '@wow-two-beta/ui/presentation/feedback';
import { Field, TextInput } from '@wow-two-beta/ui/presentation/forms';
import { Modal } from '@wow-two-beta/ui/presentation/overlays';
import { useNamespaceCreate } from '@/application/secrets';

/** Props for {@link NamespaceModal}. */
export interface NamespaceModalProps {
  vault: string;
  open: boolean;
  onOpenChange: (open: boolean) => void;
  /** Called with the new namespace's slug once the vault created it. */
  onCreated: (slug: string) => void;
}

/** Creates a vault namespace — one per product environment. */
export function NamespaceModal(props: NamespaceModalProps) {
  const creator = useNamespaceCreate(props.vault);
  const [slug, setSlug] = useState('');
  const [name, setName] = useState('');

  function close(open: boolean) {
    if (!open) {
      setSlug('');
      setName('');
    }
    props.onOpenChange(open);
  }

  async function create(event: FormEvent) {
    event.preventDefault();
    if (await creator.create(slug, name) !== null) {
      props.onCreated(slug);
      close(false);
    }
  }

  return (
    <Modal open={props.open} onOpenChange={close}>
      <Modal.Content className="w-full max-w-md">
        <form onSubmit={(event) => void create(event)}>
          <Modal.Header>
            <Modal.Title>New namespace</Modal.Title>
            <Modal.Description>One per product environment; its secrets and tokens live inside it.</Modal.Description>
          </Modal.Header>
          <Modal.Body className="flex flex-col gap-4">
            <Field label="Slug" helper="Lowercase, e.g. foreverpin-staging">
              <TextInput value={slug} onChange={(event) => setSlug(event.target.value)} autoComplete="off" required />
            </Field>
            <Field label="Name">
              <TextInput value={name} onChange={(event) => setName(event.target.value)} autoComplete="off" required />
            </Field>
            {creator.error && <Alert severity="danger" description={creator.error.message} />}
          </Modal.Body>
          <Modal.Footer>
            <Button type="button" variant="outline" tone="neutral" onClick={() => close(false)}>Cancel</Button>
            <Button type="submit" isLoading={creator.loading} isDisabled={!slug || !name}>Create namespace</Button>
          </Modal.Footer>
        </form>
      </Modal.Content>
    </Modal>
  );
}

// engineering/codebase/wheelhouse.frontend-services/src/presentation/secrets/components/NamespaceModal.vue
<script lang="ts">
/** Namespace creation dialog in the currently selected vault. */
export interface NamespaceModalProps {
  vault: string;
  open: boolean;
}
</script>

<script setup lang="ts">
import { onBeforeUnmount, watch } from "vue";
import { Button } from "@wow-two-beta/ui-vue/presentation/actions";
import { Alert } from "@wow-two-beta/ui-vue/presentation/feedback";
import { Field, TextInput } from "@wow-two-beta/ui-vue/presentation/forms";
import {
  Modal,
  ModalContent,
  ModalHeader,
  ModalTitle,
  ModalDescription,
  ModalBody,
  ModalFooter,
} from "@wow-two-beta/ui-vue/presentation/overlays";
import { useAppForm } from "@/bootstrap/form";
import { useNamespaceCreate } from "@/application/secrets";
import {
  createNamespaceForm,
  namespaceFormSchema,
} from "@/application/secrets/VaultForms";

/** Creates a namespace while preserving failed input for correction. */
defineOptions({ name: "NamespaceModal" });
const props = defineProps<NamespaceModalProps>();
const emit = defineEmits<{
  "update:open": [open: boolean];
  created: [slug: string];
}>();
defineSlots<{}>();

const creator = useNamespaceCreate(() => props.vault);
const form = useAppForm({
  defaultValues: createNamespaceForm(),
  schema: namespaceFormSchema,
  onSubmit: (values, context) =>
    creator.create(values.slug, values.name, context.signal),
});

/** Resets form ownership whenever its vault or open session changes. */
watch([() => props.open, () => props.vault], clear, { flush: "sync" });
onBeforeUnmount(clear);

/** Forgets the editor and aborts its pending submission. */
function clear(): void {
  form.invalidateSession(createNamespaceForm());
  creator.reset();
}

/** Closes the editor only on dismissal or confirmed success. */
function close(open: boolean): void {
  if (!open) clear();
  emit("update:open", open);
}

/** Submits validated input and selects the confirmed namespace. */
async function submit(event: Event): Promise<void> {
  if (await form.handleSubmit(event)) {
    emit("created", form.values.slug.trim());
    close(false);
  }
}
</script>

<template>
  <Modal :open="open" @update:open="close">
    <ModalContent class="w-full max-w-md">
      <form @submit="submit">
        <ModalHeader>
          <ModalTitle>New namespace</ModalTitle>
          <ModalDescription
            >Group one product environment's secrets and tokens
            together.</ModalDescription
          >
        </ModalHeader>
        <ModalBody class="flex flex-col gap-4">
          <form.Field name="slug" is-required v-slot="field">
            <Field label="Slug" helper="Lowercase, e.g. foreverpin-staging">
              <TextInput
                v-model="field.value"
                autocomplete="off"
                @blur="field.onBlur"
              />
            </Field>
          </form.Field>
          <form.Field name="name" is-required v-slot="field">
            <Field label="Name">
              <TextInput
                v-model="field.value"
                autocomplete="off"
                @blur="field.onBlur"
              />
            </Field>
          </form.Field>
          <Alert
            v-if="form.state.submitError"
            severity="danger"
            :description="form.state.submitError.message"
          />
        </ModalBody>
        <ModalFooter>
          <Button
            type="button"
            variant="outline"
            tone="neutral"
            @click="close(false)"
            >Cancel</Button
          >
          <Button type="submit" :is-loading="form.state.isSubmitting"
            >Create namespace</Button
          >
        </ModalFooter>
      </form>
    </ModalContent>
  </Modal>
</template>
