// engineering/codebase/wheelhouse.frontend-services/src/presentation/secrets/components/SetSecretModal.tsx
import { useState, type FormEvent } from 'react';
import { Button } from '@wow-two-beta/ui/presentation/actions';
import { Alert } from '@wow-two-beta/ui/presentation/feedback';
import { Field, PasswordInput, TextInput } from '@wow-two-beta/ui/presentation/forms';
import { Modal } from '@wow-two-beta/ui/presentation/overlays';
import { useSecretChanges } from '@/application/secrets';

/** Props for {@link SetSecretModal}. */
export interface SetSecretModalProps {
  vault: string;
  ns: string;
  /** The key being rotated; omitted when adding a new secret. */
  secretKey?: string | undefined;
  open: boolean;
  onOpenChange: (open: boolean) => void;
}

/** Writes a new secret version; the value goes to the vault and is cleared from the form immediately. */
export function SetSecretModal(props: SetSecretModalProps) {
  const changes = useSecretChanges(props.vault, props.ns);
  const [key, setKey] = useState('');
  const [value, setValue] = useState('');
  const [description, setDescription] = useState('');
  const effectiveKey = props.secretKey ?? key;

  function close(open: boolean) {
    if (!open) {
      setKey('');
      setValue('');
      setDescription('');
      changes.reset();
    }
    props.onOpenChange(open);
  }

  async function save(event: FormEvent) {
    event.preventDefault();
    const saved = await changes.set(effectiveKey, value, description || undefined);
    setValue('');
    if (saved !== null) close(false);
  }

  return (
    <Modal open={props.open} onOpenChange={close}>
      <Modal.Content>
        <form onSubmit={(event) => void save(event)}>
          <Modal.Header>
            <Modal.Title>{props.secretKey ? `Rotate ${props.secretKey}` : 'Add secret'}</Modal.Title>
            <Modal.Description>
              The value goes straight to the vault as a new version. Wheelhouse never shows it again.
            </Modal.Description>
          </Modal.Header>
          <Modal.Body className="flex flex-col gap-3">
            {!props.secretKey && (
              <Field label="Key" helper="e.g. DATABASE_URL or Billing:SecretKey">
                <TextInput value={key} onChange={(event) => setKey(event.target.value)} autoComplete="off" required />
              </Field>
            )}
            <Field label="Value">
              <PasswordInput value={value} onChange={(event) => setValue(event.target.value)} autoComplete="new-password" required />
            </Field>
            <Field label="Description">
              <TextInput value={description} onChange={(event) => setDescription(event.target.value)} autoComplete="off" />
            </Field>
            {changes.error && <Alert severity="danger" description={changes.error.message} />}
          </Modal.Body>
          <Modal.Footer>
            <Button variant="outline" tone="neutral" onClick={() => close(false)}>Cancel</Button>
            <Button type="submit" isLoading={changes.loading} isDisabled={!effectiveKey || !value}>Save version</Button>
          </Modal.Footer>
        </form>
      </Modal.Content>
    </Modal>
  );
}

// engineering/codebase/wheelhouse.frontend-services/src/presentation/secrets/components/SetSecretModal.vue
<script lang="ts">
/** Local secret editing session, optionally bound to an immutable rotation key. */
export interface SetSecretModalProps {
  vault: string;
  ns: string;
  secretKey?: string | undefined;
  open: boolean;
}
</script>

<script setup lang="ts">
import { onBeforeUnmount, watch } from "vue";
import { Button } from "@wow-two-beta/ui-vue/presentation/actions";
import { Alert } from "@wow-two-beta/ui-vue/presentation/feedback";
import {
  Field,
  PasswordInput,
  TextInput,
} from "@wow-two-beta/ui-vue/presentation/forms";
import {
  Modal,
  ModalContent,
  ModalHeader,
  ModalTitle,
  ModalDescription,
  ModalBody,
  ModalFooter,
} from "@wow-two-beta/ui-vue/presentation/overlays";
import { useAppForm } from "@/bootstrap/form";
import { useSecretChanges } from "@/application/secrets";
import {
  createSecretForm,
  secretFormSchema,
} from "@/application/secrets/VaultForms";

/** Writes a secret version without caching or persisting its plaintext. */
defineOptions({ name: "SetSecretModal" });
const props = defineProps<SetSecretModalProps>();
const emit = defineEmits<{ "update:open": [open: boolean] }>();
defineSlots<{}>();

const changes = useSecretChanges(
  () => props.vault,
  () => props.ns,
);
const form = useAppForm({
  defaultValues: createSecretForm(props.secretKey),
  schema: secretFormSchema,
  onSubmit: (values, context) =>
    changes.set(
      values.key,
      values.value,
      values.description || undefined,
      context.signal,
    ),
});

/** Discards plaintext immediately on close, target change, or a different rotation key. */
watch(
  [() => props.open, () => props.vault, () => props.ns, () => props.secretKey],
  clear,
  { flush: "sync" },
);
onBeforeUnmount(clear);

/** Invalidates pending work and empties both editable values and the form baseline. */
function clear(): void {
  form.invalidateSession(createSecretForm(props.secretKey));
  changes.reset();
}

/** Forgets the plaintext whenever the dialog is dismissed. */
function close(open: boolean): void {
  if (!open) clear();
  emit("update:open", open);
}

/** Closes only on confirmed success; failed input remains editable in the current session. */
async function submit(event: Event): Promise<void> {
  if (await form.handleSubmit(event)) close(false);
}
</script>

<template>
  <Modal :open="open" @update:open="close">
    <ModalContent>
      <form @submit="submit">
        <ModalHeader>
          <ModalTitle>{{
            secretKey ? `Rotate ${secretKey}` : "Add secret"
          }}</ModalTitle>
          <ModalDescription>
            The vault receives a new version. Wheelhouse only displays its
            metadata afterwards.
          </ModalDescription>
        </ModalHeader>
        <ModalBody class="flex flex-col gap-4">
          <form.Field v-if="!secretKey" name="key" is-required v-slot="field">
            <Field label="Key" helper="e.g. DATABASE_URL or Billing:SecretKey">
              <TextInput
                v-model="field.value"
                autocomplete="off"
                @blur="field.onBlur"
              />
            </Field>
          </form.Field>
          <form.Field name="value" is-required v-slot="field">
            <Field label="Value">
              <PasswordInput
                v-model="field.value"
                autocomplete="new-password"
                @blur="field.onBlur"
              />
            </Field>
          </form.Field>
          <form.Field name="description" v-slot="field">
            <Field label="Description">
              <TextInput
                v-model="field.value"
                autocomplete="off"
                @blur="field.onBlur"
              />
            </Field>
          </form.Field>
          <Alert
            v-if="form.state.submitError"
            severity="danger"
            :description="form.state.submitError.message"
          />
        </ModalBody>
        <ModalFooter>
          <Button
            type="button"
            variant="outline"
            tone="neutral"
            @click="close(false)"
            >Cancel</Button
          >
          <Button type="submit" :is-loading="form.state.isSubmitting"
            >Save version</Button
          >
        </ModalFooter>
      </form>
    </ModalContent>
  </Modal>
</template>
