// engineering/codebase/wheelhouse.frontend-services/src/presentation/deployments/components/DeployModal.vue
<script lang="ts">
/** Defines a target and release bundle preselected for a new deployment session. */
export interface DeploySelection {
  readonly target: string;
  readonly release: string;
}

/** Defines the controlled deployment dialog and its initial selection. */
export interface DeployModalProps {
  /** The controlled dialog state. */
  readonly open: boolean;
  /** The selection applied on opening; each new session resets the workflow. */
  readonly selection?: DeploySelection | null;
}
</script>

<script setup lang="ts">
import { computed, ref, shallowRef, watch } from "vue";
import { ArrowLeft, Rocket, ShieldCheck } from "lucide-vue-next";

import { Button } from "@wow-two-beta/ui-vue/presentation/actions";
import { Alert, Spinner } from "@wow-two-beta/ui-vue/presentation/feedback";
import {
  Field,
  SelectPicker,
  SelectPickerContent,
  SelectPickerItem,
  SelectPickerTrigger,
  SelectPickerValue,
} from "@wow-two-beta/ui-vue/presentation/forms";
import {
  Modal,
  ModalBody,
  ModalContent,
  ModalDescription,
  ModalFooter,
  ModalHeader,
  ModalTitle,
} from "@wow-two-beta/ui-vue/presentation/overlays";

import {
  useDeploymentOutcome,
  useDeploymentTargets,
  useReleaseArtifacts,
  useStartDeployment,
  useTargetCheck,
} from "@/application/deployments";
import {
  JobStatus,
  type DeploymentTarget,
  type ReleaseArtifact,
  type TargetCheck,
} from "@/domain/deployments";

import CheckResultList from "./CheckResultList.vue";
import JobStatusBadge from "./JobStatusBadge.vue";

/** Renders choose, confirm and follow stages for deploying one complete release bundle. */
defineOptions({ name: "DeployModal" });
const props = defineProps<DeployModalProps>();
const emit = defineEmits<{ "update:open": [open: boolean] }>();
const targets = useDeploymentTargets();
const releases = useReleaseArtifacts();
const check = useTargetCheck();
const start = useStartDeployment();
const step = ref<"choose" | "confirm" | "follow">("choose");
const target = ref("");
const release = ref("");
const jobId = ref<string | null>(null);
const readiness = shallowRef<TargetCheck | null>(null);
const outcome = useDeploymentOutcome(jobId);
const selectedTarget = computed(() =>
  targets.data.value?.find((item) => item.id === target.value),
);
const available = computed(() =>
  (releases.data.value ?? []).filter(
    (item) => item.product === selectedTarget.value?.product,
  ),
);
const selectedRelease = computed(() =>
  available.value.find((item) => item.id === release.value),
);
const inventoryError = computed(
  () => targets.error.value ?? releases.error.value,
);
const canChoose = computed(() =>
  Boolean(selectedTarget.value && selectedRelease.value),
);
const lockedFailure = computed(
  () =>
    outcome.data.value?.mutationStarted &&
    (outcome.data.value.status === JobStatus.Failed ||
      outcome.data.value.status === JobStatus.RollbackFailed),
);

/** Starts a fresh selection when the controlled dialog opens. */
watch(
  () => props.open,
  (open) => {
    if (!open) return;
    step.value = "choose";
    target.value = props.selection?.target ?? "";
    release.value = props.selection?.release ?? "";
    jobId.value = null;
    readiness.value = null;
    check.reset();
    start.reset();
    void releases.refetch();
  },
  { immediate: true },
);

/** Clears readiness whenever its exact target or release changes. */
watch([target, release], () => {
  readiness.value = null;
  check.reset();
});

/** Formats an actual runner target for the environment picker. */
function targetLabel(item?: DeploymentTarget): string {
  return item ? `${item.product} · ${item.environment} · ${item.host}` : "";
}

/** Formats a catalog release without substituting a bundle identifier. */
function releaseLabel(item?: ReleaseArtifact): string {
  return item ? item.release + (item.prerelease ? " (prerelease)" : "") : "";
}

/** Changes targets and clears the incompatible bundle selection. */
function selectTarget(value: string | null): void {
  target.value = value ?? "";
  release.value = "";
}

/** Records readiness only if the inspected target and bundle remain selected. */
async function inspect(): Promise<void> {
  if (!selectedTarget.value || check.loading.value) return;
  const inspectedTarget = target.value;
  const inspectedRelease = release.value;
  const result = await check.mutateAsync({
    target: inspectedTarget,
    ...(inspectedRelease ? { release: inspectedRelease } : {}),
  });
  if (
    result.ok &&
    target.value === inspectedTarget &&
    release.value === inspectedRelease
  )
    readiness.value = result.value;
}

/** Enters confirmation only for a bundle belonging to the selected target's literal product. */
function confirmSelection(): void {
  if (canChoose.value) step.value = "confirm";
}

/** Submits the confirmed bundle and follows only an acknowledged submission. */
async function deploy(): Promise<void> {
  if (!canChoose.value || start.loading.value) return;
  const result = await start.mutateAsync({
    target: target.value,
    release: release.value,
  });
  if (!result.ok) return;
  jobId.value = result.value.id;
  step.value = "follow";
}

/** Requests dismissal without interrupting an already submitted rollout. */
function close(open: boolean): void {
  if (start.loading.value) return;
  emit("update:open", open);
}
</script>

<template>
  <Modal
    :open="props.open"
    :dismiss-on-outside-click="!start.loading.value"
    :dismiss-on-escape="!start.loading.value"
    @update:open="close"
  >
    <ModalContent class="w-full max-w-xl">
      <template v-if="step === 'choose'">
        <ModalHeader>
          <ModalTitle>Deploy a release</ModalTitle>
          <ModalDescription
            >Choose an environment and a published release, then check
            readiness.</ModalDescription
          >
        </ModalHeader>
        <ModalBody class="flex flex-col gap-4">
          <div
            v-if="targets.loading.value || releases.loading.value"
            class="flex justify-center py-6"
          >
            <Spinner label="Loading targets and releases" />
          </div>
          <Alert
            v-else-if="inventoryError"
            severity="danger"
            title="Couldn't load deployment inventory"
            :description="inventoryError.message"
          >
            <template #actions>
              <Button
                variant="soft"
                tone="danger"
                size="sm"
                @click="
                  targets.refetch();
                  releases.refetch();
                "
                >Retry</Button
              >
            </template>
          </Alert>
          <Alert
            v-else-if="!targets.data.value?.length"
            severity="info"
            title="No deployment targets"
            description="No deployment environment has been configured for this workspace."
          />
          <template v-else>
            <Field label="Environment">
              <SelectPicker
                :model-value="target || null"
                :is-disabled="check.loading.value"
                :get-option-label="
                  (key: string) =>
                    targetLabel(
                      targets.data.value?.find((item) => item.id === key),
                    )
                "
                @update:model-value="selectTarget"
              >
                <SelectPickerTrigger aria-label="Environment">
                  <SelectPickerValue placeholder="Select an environment" />
                </SelectPickerTrigger>
                <SelectPickerContent>
                  <SelectPickerItem
                    v-for="item in targets.data.value"
                    :key="item.id"
                    :item-key="item.id"
                    :label="targetLabel(item)"
                  />
                </SelectPickerContent>
              </SelectPicker>
            </Field>
            <Field
              label="Release"
              :helper="
                target && !available.length
                  ? 'No published release is available yet.'
                  : ''
              "
            >
              <SelectPicker
                :model-value="release || null"
                :is-disabled="!available.length || check.loading.value"
                :get-option-label="
                  (key: string) =>
                    releaseLabel(available.find((item) => item.id === key))
                "
                @update:model-value="
                  (value: string | null) => (release = value ?? '')
                "
              >
                <SelectPickerTrigger aria-label="Release">
                  <SelectPickerValue placeholder="Select a published release" />
                </SelectPickerTrigger>
                <SelectPickerContent>
                  <SelectPickerItem
                    v-for="item in available"
                    :key="item.id"
                    :item-key="item.id"
                    :label="releaseLabel(item)"
                  />
                </SelectPickerContent>
              </SelectPicker>
            </Field>
            <Alert
              v-if="check.error.value"
              severity="danger"
              title="Check unavailable"
              :description="check.error.value.message"
            />
            <div
              v-if="readiness"
              class="flex flex-col gap-3 rounded-xl border border-border p-4"
            >
              <p class="text-sm font-medium">
                {{
                  readiness.ok
                    ? "Ready to deploy"
                    : "Resolve failed checks before deploying"
                }}
              </p>
              <CheckResultList :check="readiness" />
            </div>
          </template>
        </ModalBody>
        <ModalFooter>
          <Button
            variant="outline"
            tone="neutral"
            :is-loading="check.loading.value"
            :is-disabled="!selectedTarget"
            @click="inspect"
          >
            <template #leading><ShieldCheck :size="16" /></template>
            Check readiness
          </Button>
          <Button
            variant="solid"
            tone="primary"
            :is-disabled="!canChoose || check.loading.value"
            @click="confirmSelection"
            >Continue</Button
          >
        </ModalFooter>
      </template>
      <template v-else-if="step === 'confirm'">
        <ModalHeader>
          <ModalTitle
            >Deploy {{ selectedRelease?.release }} to {{ target }}?</ModalTitle
          >
          <ModalDescription>
            The target pulls every image, replaces its containers, and waits for
            health and smoke checks. Replacement includes a short restart
            window.
          </ModalDescription>
        </ModalHeader>
        <ModalBody class="flex flex-col gap-4">
          <dl
            class="grid grid-cols-[auto_1fr] gap-x-4 gap-y-3 rounded-xl border border-border p-4 text-sm"
          >
            <dt class="text-muted-foreground">Environment</dt>
            <dd>{{ targetLabel(selectedTarget) }}</dd>
            <dt class="text-muted-foreground">Release</dt>
            <dd class="font-mono">{{ releaseLabel(selectedRelease) }}</dd>
            <dt class="text-muted-foreground">Readiness</dt>
            <dd>
              {{
                !readiness
                  ? "Not checked"
                  : readiness.ok
                    ? "Ready"
                    : "Failed checks; the runner refuses deployment"
              }}
            </dd>
          </dl>
          <Alert
            v-if="!canChoose"
            severity="warning"
            description="The selected target or release is no longer available."
          />
          <Alert
            v-if="start.error.value"
            severity="danger"
            title="Deployment refused"
            :description="start.error.value.message"
          />
        </ModalBody>
        <ModalFooter>
          <Button
            variant="outline"
            tone="neutral"
            :is-disabled="start.loading.value"
            @click="step = 'choose'"
          >
            <template #leading><ArrowLeft :size="16" /></template>Back
          </Button>
          <Button
            variant="solid"
            tone="primary"
            :is-loading="start.loading.value"
            :is-disabled="!canChoose"
            @click="deploy"
          >
            <template #leading><Rocket :size="16" /></template>Deploy
          </Button>
        </ModalFooter>
      </template>
      <template v-else>
        <ModalHeader>
          <ModalTitle
            >{{
              outcome.pending.value || !outcome.data.value
                ? "Deploying"
                : "Deployment settled"
            }}
            {{ selectedRelease?.release }}</ModalTitle
          >
          <ModalDescription
            >Closing keeps the rollout running. Deployment history records its
            outcome.</ModalDescription
          >
        </ModalHeader>
        <ModalBody class="flex flex-col gap-4">
          <div
            role="status"
            class="flex flex-col gap-3 rounded-xl border border-border p-4"
          >
            <div class="flex flex-wrap items-center gap-2 text-sm">
              <span
                >Deployment
                <span class="font-mono">{{ jobId?.slice(0, 8) }}</span></span
              >
              <JobStatusBadge
                v-if="outcome.data.value"
                :status="outcome.data.value.status"
              />
              <Spinner v-else size="sm" label="Waiting for the runner" />
            </div>
            <p
              v-if="outcome.data.value?.reason"
              class="text-sm text-muted-foreground"
            >
              {{ outcome.data.value.reason }}
            </p>
          </div>
          <Alert
            v-if="lockedFailure"
            severity="warning"
            description="The target stays locked until an operator inspects and reconciles it."
          />
          <Alert
            v-if="outcome.error.value"
            severity="warning"
            title="Outcome unavailable"
            :description="outcome.error.value.message"
          >
            <template #actions>
              <Button
                size="sm"
                variant="outline"
                tone="neutral"
                @click="outcome.refetch()"
                >Retry</Button
              >
            </template>
          </Alert>
        </ModalBody>
        <ModalFooter
          ><Button variant="outline" tone="neutral" @click="close(false)"
            >Close</Button
          ></ModalFooter
        >
      </template>
    </ModalContent>
  </Modal>
</template>

// engineering/codebase/wheelhouse.frontend-services/src/presentation/deployments/components/DeployModal.tsx
import { useEffect, useState } from 'react';
import { ArrowLeft, Rocket, ShieldCheck } from 'lucide-react';
import { Button } from '@wow-two-beta/ui/presentation/actions';
import { Text } from '@wow-two-beta/ui/presentation/display';
import { Alert, Spinner } from '@wow-two-beta/ui/presentation/feedback';
import { Field, Select } from '@wow-two-beta/ui/presentation/forms';
import { Modal } from '@wow-two-beta/ui/presentation/overlays';
import {
  useDeploymentOutcome,
  useDeploymentTargets,
  useReleaseArtifacts,
  useStartDeployment,
  useTargetCheck,
} from '@/application/deployments';
import { JobStatus, type DeploymentTarget, type ReleaseArtifact } from '@/domain/deployments';
import { CheckResultList } from './CheckResultList';
import { JobStatusBadge } from './JobStatusBadge';

const targetLabel = (item?: DeploymentTarget) => item && `${item.product} · ${item.environment} · ${item.host}`;
const releaseLabel = (item?: ReleaseArtifact) => item && item.release + (item.prerelease ? ' (prerelease)' : '');

/** A target and release to preselect, such as a redeploy chosen from the history. */
export interface DeploySelection {
  target: string;
  release: string;
}

/** Props for {@link DeployModal}. */
export interface DeployModalProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  /** Where to start; remount the modal (a new `key`) for each opening so it starts fresh. */
  selection?: DeploySelection | null;
}

// Choose a target and release, confirm the replacement, then follow the outcome.
type Step = 'choose' | 'confirm' | 'follow';

/** Checks a target and deploys a published release to it, then follows the outcome until it settles. */
export function DeployModal(props: DeployModalProps) {
  const targets = useDeploymentTargets();
  const releases = useReleaseArtifacts();
  const check = useTargetCheck();
  const start = useStartDeployment();
  const [step, setStep] = useState<Step>('choose');
  const [target, setTarget] = useState(props.selection?.target ?? '');
  const [release, setRelease] = useState(props.selection?.release ?? '');
  const [jobId, setJobId] = useState<string | null>(null);
  const outcome = useDeploymentOutcome(jobId);
  const { refetch: refetchReleases } = releases;

  const selectedTarget = targets.data?.find((item) => item.id === target);
  const available = (releases.data ?? []).filter((item) => item.product === selectedTarget?.product);
  const selectedRelease = available.find((item) => item.id === release);

  // ---- Each opening lists the newest published releases ----
  useEffect(() => {
    if (props.open) void refetchReleases();
  }, [props.open, refetchReleases]);

  function selectTarget(value: string) {
    setTarget(value);
    setRelease('');
    check.reset();
  }

  async function deploy() {
    const job = await start.mutateAsync({ target, release }).catch(() => null);
    if (job) {
      setJobId(job.id);
      setStep('follow');
    }
  }

  return (
    <Modal open={props.open} onOpenChange={props.onOpenChange}>
      <Modal.Content className="w-full max-w-xl">
        {step === 'choose' && (
          <>
            <Modal.Header>
              <Modal.Title>Deploy a release</Modal.Title>
              <Modal.Description>Pick an environment and a published release; check readiness before you deploy.</Modal.Description>
            </Modal.Header>
            <Modal.Body className="flex flex-col gap-4">
              {targets.loading || releases.loading ? (
                <div className="flex justify-center py-6"><Spinner label="Loading targets and releases" /></div>
              ) : targets.error ?? releases.error ? (
                <Alert severity="danger" title="Couldn't load" description={(targets.error ?? releases.error)?.message} />
              ) : !targets.data?.length ? (
                <Alert severity="info" title="No deployment targets" description="Targets are defined in reviewed code (fleet.py)." />
              ) : (
                <>
                  <Field label="Environment">
                    <Select<string> value={target || null} onValueChange={(option) => selectTarget(option?.value ?? '')}
                      getOptionLabel={(key) => targetLabel(targets.data?.find((item) => item.id === key)) ?? key}>
                      <Select.Trigger aria-label="Environment"><Select.Value placeholder="Select an environment" /></Select.Trigger>
                      <Select.Content>
                        {(targets.data ?? []).map((item) => (
                          <Select.Item key={item.id} itemKey={item.id} label={targetLabel(item)} />
                        ))}
                      </Select.Content>
                    </Select>
                  </Field>
                  <Field label="Release" helper={target && !available.length ? 'No published release for this product yet.' : undefined}>
                    <Select<string> value={release || null} onValueChange={(option) => setRelease(option?.value ?? '')}
                      isDisabled={!available.length} getOptionLabel={(key) => releaseLabel(available.find((item) => item.id === key)) ?? key}>
                      <Select.Trigger aria-label="Release"><Select.Value placeholder="Select a published release" /></Select.Trigger>
                      <Select.Content>
                        {available.map((item) => (
                          <Select.Item key={item.id} itemKey={item.id} label={releaseLabel(item)} />
                        ))}
                      </Select.Content>
                    </Select>
                  </Field>
                  {check.error && <Alert severity="danger" title="Check unavailable" description={check.error.message} />}
                  {check.data && (
                    <div className="flex flex-col gap-2 rounded-lg border border-border p-4">
                      <Text size="sm" weight="medium">
                        {check.data.ok ? 'Ready to deploy' : 'Not ready — resolve the failed checks first'}
                      </Text>
                      <CheckResultList check={check.data} />
                    </div>
                  )}
                </>
              )}
            </Modal.Body>
            <Modal.Footer>
              <Button variant="outline" tone="neutral" leadingSlot={<ShieldCheck size={16} />} isLoading={check.loading}
                isDisabled={!target} onClick={() => check.mutate({ target, ...(release ? { release } : {}) })}>
                Check readiness
              </Button>
              <Button variant="solid" tone="primary" isDisabled={!selectedRelease} onClick={() => setStep('confirm')}>
                Continue
              </Button>
            </Modal.Footer>
          </>
        )}

        {step === 'confirm' && (
          <>
            <Modal.Header>
              <Modal.Title>Deploy {selectedRelease?.release} to {target}?</Modal.Title>
              <Modal.Description>
                The target pulls every image first, then replaces its containers and waits for health and smoke checks.
                Replacement has a short restart window.
              </Modal.Description>
            </Modal.Header>
            <Modal.Body className="flex flex-col gap-3">
              <dl className="grid grid-cols-[auto_1fr] gap-x-4 gap-y-2 rounded-lg border border-border p-4 text-sm">
                <dt className="text-muted-foreground">Environment</dt>
                <dd>{targetLabel(selectedTarget)}</dd>
                <dt className="text-muted-foreground">Release</dt>
                <dd className="font-mono">{releaseLabel(selectedRelease)}</dd>
                <dt className="text-muted-foreground">Readiness</dt>
                <dd>{!check.data ? 'Not checked' : check.data.ok ? 'Ready' : 'Failed checks — the runner refuses the deploy'}</dd>
              </dl>
              {start.error && <Alert severity="danger" title="Deployment refused" description={start.error.message} />}
            </Modal.Body>
            <Modal.Footer>
              <Button variant="outline" tone="neutral" leadingSlot={<ArrowLeft size={16} />} isDisabled={start.loading}
                onClick={() => setStep('choose')}>
                Back
              </Button>
              <Button variant="solid" tone="primary" leadingSlot={<Rocket size={16} />} isLoading={start.loading}
                onClick={() => void deploy()}>
                Deploy
              </Button>
            </Modal.Footer>
          </>
        )}

        {step === 'follow' && (
          <>
            <Modal.Header>
              <Modal.Title>{outcome.pending || !outcome.data ? 'Deploying' : 'Deployment settled'} {selectedRelease?.release}</Modal.Title>
              <Modal.Description>Closing this keeps the rollout running; the history records its outcome.</Modal.Description>
            </Modal.Header>
            <Modal.Body className="flex flex-col gap-3">
              <div role="status" className="flex flex-col gap-2 rounded-lg border border-border p-4">
                <div className="flex flex-wrap items-center gap-2">
                  <Text size="sm">Deployment <span className="font-mono">{jobId?.slice(0, 8)}</span></Text>
                  {outcome.data ? <JobStatusBadge status={outcome.data.status} /> : <Spinner size="sm" label="Waiting for the runner" />}
                </div>
                {outcome.data?.reason && <Text size="sm" color="muted">{outcome.data.reason}</Text>}
              </div>
              {outcome.data?.mutationStarted
                && (outcome.data.status === JobStatus.Failed || outcome.data.status === JobStatus.RollbackFailed) && (
                <Alert severity="warning" description="The target stays locked until an operator reconciles it under Targets." />
              )}
              {outcome.error && <Alert severity="warning" title="Outcome unavailable" description={outcome.error.message} />}
            </Modal.Body>
            <Modal.Footer>
              <Button variant="outline" tone="neutral" onClick={() => props.onOpenChange(false)}>Close</Button>
            </Modal.Footer>
          </>
        )}
      </Modal.Content>
    </Modal>
  );
}
