// engineering/codebase/wheelhouse.frontend-services/src/presentation/deployments/components/ReconcileModal.vue
<script lang="ts">
import type { RolloutRecord } from "@/domain/deployments";

/** Defines the exact locked target and remote rollout the operator will acknowledge. */
export interface ReconcileModalProps {
  /** The literal runner target identifier. */
  readonly target: string;
  /** The active remote rollout, whose ID differs from its submission ID. */
  readonly active: RolloutRecord;
  /** The controlled dialog state. */
  readonly open: boolean;
}
</script>

<script setup lang="ts">
import { computed, ref, watch } from "vue";

import { Button } from "@wow-two-beta/ui-vue/presentation/actions";
import { Alert } from "@wow-two-beta/ui-vue/presentation/feedback";
import { Field, TextInput } from "@wow-two-beta/ui-vue/presentation/forms";
import {
  AlertModal,
  AlertModalContent,
  ModalBody,
  ModalDescription,
  ModalFooter,
  ModalHeader,
  ModalTitle,
} from "@wow-two-beta/ui-vue/presentation/overlays";

import { useReconcileTarget } from "@/application/deployments";

/** Renders typed confirmation before acknowledging an inspected remote rollout. */
defineOptions({ name: "ReconcileModal" });
const props = defineProps<ReconcileModalProps>();
const emit = defineEmits<{ "update:open": [open: boolean] }>();
const reconcile = useReconcileTarget();
const typed = ref("");
const confirmed = computed(() => typed.value === props.target);

/** Resets confirmation when its target or active rollout changes. */
watch(
  () => [props.open, props.target, props.active.id],
  () => {
    typed.value = "";
    reconcile.reset();
  },
);

/** Requests dismissal without acknowledging anything. */
function close(open: boolean): void {
  if (reconcile.loading.value) return;
  emit("update:open", open);
}

/** Acknowledges the exact remote rollout only after matching the target name. */
async function confirm(): Promise<void> {
  if (!confirmed.value || reconcile.loading.value) return;
  const target = props.target;
  const job = props.active.id;
  const result = await reconcile.mutateAsync({
    target,
    job,
  });
  if (result.ok && props.target === target && props.active.id === job)
    emit("update:open", false);
}
</script>

<template>
  <AlertModal
    :open="props.open"
    :dismiss-on-escape="!reconcile.loading.value"
    @update:open="close"
  >
    <AlertModalContent>
      <ModalHeader>
        <ModalTitle>Reconcile {{ props.target }}?</ModalTitle>
        <ModalDescription>
          Confirm after inspecting this target's containers and database schema.
          Reconciliation marks the rollout interrupted and clears its automatic
          rollback pointer. Containers and data stay unchanged.
        </ModalDescription>
      </ModalHeader>
      <ModalBody class="flex flex-col gap-4">
        <p class="text-sm text-muted-foreground">
          Stopped rollout: {{ props.active.release ?? props.active.id }}
          <span v-if="props.active.reason"> · {{ props.active.reason }}</span>
        </p>
        <Field :label="`Type ${props.target} to confirm`">
          <TextInput
            v-model="typed"
            :disabled="reconcile.loading.value"
            autocomplete="off"
          />
        </Field>
        <Alert
          v-if="reconcile.error.value"
          severity="danger"
          :description="reconcile.error.value.message"
        />
      </ModalBody>
      <ModalFooter>
        <Button
          variant="outline"
          tone="neutral"
          :is-disabled="reconcile.loading.value"
          @click="close(false)"
        >
          Cancel
        </Button>
        <Button
          variant="solid"
          tone="danger"
          :is-disabled="!confirmed"
          :is-loading="reconcile.loading.value"
          @click="confirm"
          >Reconcile</Button
        >
      </ModalFooter>
    </AlertModalContent>
  </AlertModal>
</template>

// engineering/codebase/wheelhouse.frontend-services/src/presentation/deployments/components/ReconcileModal.tsx
import { useState } from 'react';
import { Button } from '@wow-two-beta/ui/presentation/actions';
import { Text } from '@wow-two-beta/ui/presentation/display';
import { Alert } from '@wow-two-beta/ui/presentation/feedback';
import { Field, TextInput } from '@wow-two-beta/ui/presentation/forms';
import { AlertModal } from '@wow-two-beta/ui/presentation/overlays';
import { useReconcileTarget } from '@/application/deployments';
import type { RolloutRecord } from '@/domain/deployments';

/** Props for {@link ReconcileModal}. */
export interface ReconcileModalProps {
  target: string;
  active: RolloutRecord;
  open: boolean;
  onOpenChange: (open: boolean) => void;
}

/** Confirms that the operator inspected a locked target before it accepts deployments again. */
export function ReconcileModal(props: ReconcileModalProps) {
  const reconcile = useReconcileTarget();
  const [typed, setTyped] = useState('');
  const confirmed = typed === props.target;

  function close(open: boolean) {
    if (!open) {
      setTyped('');
      reconcile.reset();
    }
    props.onOpenChange(open);
  }

  async function confirm() {
    const done = await reconcile.mutateAsync({ target: props.target, job: props.active.id }).catch(() => null);
    if (done) close(false);
  }

  return (
    <AlertModal open={props.open} onOpenChange={close}>
      <AlertModal.Content>
        <AlertModal.Header>
          <AlertModal.Title>Reconcile {props.target}?</AlertModal.Title>
          <AlertModal.Description>
            Confirm only after inspecting the target's containers and database schema. Reconciling marks the
            rollout interrupted and clears the automatic-rollback pointer; it changes no containers or data.
          </AlertModal.Description>
        </AlertModal.Header>
        <AlertModal.Body className="flex flex-col gap-3">
          <Text size="sm" color="muted">
            Stopped rollout: {props.active.release ?? props.active.id}
            {props.active.reason ? ` — ${props.active.reason}` : ''}
          </Text>
          <Field label={`Type ${props.target} to confirm`}>
            <TextInput value={typed} onChange={(event) => setTyped(event.target.value)} autoComplete="off" />
          </Field>
          {reconcile.error && <Alert severity="danger" description={reconcile.error.message} />}
        </AlertModal.Body>
        <AlertModal.Footer>
          <Button variant="outline" tone="neutral" onClick={() => close(false)}>Cancel</Button>
          <Button variant="solid" tone="danger" isDisabled={!confirmed} isLoading={reconcile.loading}
            onClick={() => void confirm()}>
            Reconcile
          </Button>
        </AlertModal.Footer>
      </AlertModal.Content>
    </AlertModal>
  );
}
