// engineering/codebase/wheelhouse.frontend-services/apps/web/src/presentation/products/components/RegisterProductForm.vue
<script lang="ts">
import type { ProductOperations } from "@/application/products";
import type { Product } from "@/domain/products";

/** Inputs seed one create or edit form instance; the parent keys edited products by ID. */
export interface RegisterProductFormProps {
  readonly initialProduct?: Product;
  readonly create: ProductOperations["create"];
  readonly update: ProductOperations["update"];
}
</script>

<script setup lang="ts">
import { computed, watch } from "vue";
import { z } from "zod";
import { Button } from "@wow-two-beta/ui-vue/presentation/actions";
import { Alert } from "@wow-two-beta/ui-vue/presentation/feedback";
import {
  Field,
  TextInput,
  SelectPicker,
  SelectPickerTrigger,
  SelectPickerValue,
  SelectPickerContent,
  SelectPickerItem,
} from "@wow-two-beta/ui-vue/presentation/forms";
import { useAppForm } from "@/bootstrap/form";
import { parseRepoInput, ProductStatus } from "@/domain/products";

/** Edits a product with inline validation and resets only after confirmed success. */
defineOptions({ name: "RegisterProductForm" });
const props = defineProps<RegisterProductFormProps>();
const emit = defineEmits<{
  saved: [];
  cancel: [];
  pending: [value: boolean];
}>();

const statuses = Object.values(ProductStatus);
const schema = z.object({
  slug: z.string().trim().min(1, "Slug is required"),
  name: z.string().trim().min(1, "Name is required"),
  repo: z.string().superRefine((value, context) => {
    const parsed = parseRepoInput(value);
    if (parsed.provider === null)
      context.addIssue({ code: "custom", message: parsed.error });
  }),
  status: z.enum(ProductStatus),
});
const form = useAppForm({
  defaultValues: {
    slug: props.initialProduct?.slug ?? "",
    name: props.initialProduct?.name ?? "",
    repo: props.initialProduct?.repo ?? "",
    status: props.initialProduct?.status ?? ProductStatus.Draft,
  },
  schema,
  onSubmit: (values) => {
    const parsed = parseRepoInput(values.repo);
    const repo = parsed.provider === null ? values.repo.trim() : parsed.repo;
    return props.initialProduct
      ? props.update(props.initialProduct.id, {
          name: values.name.trim(),
          repo,
          status: values.status,
        })
      : props.create({
          slug: values.slug.trim(),
          name: values.name.trim(),
          repo,
        });
  },
});
const editing = computed(() => props.initialProduct !== undefined);

/** Exposes submission state so the surrounding modal cannot dismiss a pending write. */
watch(
  () => form.state.isSubmitting,
  (pending) => emit("pending", pending),
);

/** Preserves invalid input while normalizing accepted GitHub references. */
function normalizeRepo(value: string): void {
  const parsed = parseRepoInput(value);
  form.setValue("repo", parsed.provider === null ? value : parsed.repo);
}

/** Closes the editor only after schema validation and server confirmation. */
async function submit(event: Event): Promise<void> {
  if (await form.handleSubmit(event)) emit("saved");
}
</script>

<template>
  <form class="flex flex-col gap-5" @submit.prevent="submit">
    <div class="grid gap-5 sm:grid-cols-2">
      <form.Field
        v-slot="field"
        name="name"
        :is-disabled="form.state.isSubmitting"
      >
        <Field label="Product name">
          <TextInput
            v-model="field.value"
            placeholder="My product"
            autocomplete="off"
            @blur="field.onBlur"
          />
        </Field>
      </form.Field>
      <form.Field
        v-slot="field"
        name="slug"
        :is-disabled="editing || form.state.isSubmitting"
      >
        <Field
          label="Slug"
          :helper="
            editing
              ? 'The product identifier stays fixed.'
              : 'A stable product identifier.'
          "
        >
          <TextInput
            v-model="field.value"
            placeholder="my-product"
            autocomplete="off"
            @blur="field.onBlur"
          />
        </Field>
      </form.Field>
    </div>
    <div class="grid gap-5 sm:grid-cols-[10rem_1fr]">
      <Field label="Provider">
        <SelectPicker
          model-value="github"
          :is-disabled="form.state.isSubmitting"
        >
          <SelectPickerTrigger class="w-full"
            ><SelectPickerValue
          /></SelectPickerTrigger>
          <SelectPickerContent>
            <SelectPickerItem item-key="github" label="GitHub" />
            <SelectPickerItem
              item-key="gitlab"
              label="GitLab (soon)"
              is-disabled
            />
            <SelectPickerItem
              item-key="bitbucket"
              label="Bitbucket (soon)"
              is-disabled
            />
          </SelectPickerContent>
        </SelectPicker>
      </Field>
      <form.Field
        v-slot="field"
        name="repo"
        :is-disabled="form.state.isSubmitting"
      >
        <Field
          label="Repository"
          helper="Paste a GitHub URL, SSH remote, or owner/repo."
        >
          <TextInput
            :model-value="String(field.value)"
            placeholder="owner/repository"
            autocomplete="off"
            @update:model-value="normalizeRepo"
            @blur="field.onBlur"
          />
        </Field>
      </form.Field>
    </div>
    <form.Field
      v-if="editing"
      v-slot="field"
      name="status"
      :is-disabled="form.state.isSubmitting"
    >
      <Field label="Lifecycle">
        <SelectPicker
          :model-value="String(field.value)"
          @update:model-value="field.setValue"
        >
          <SelectPickerTrigger class="w-full"
            ><SelectPickerValue
          /></SelectPickerTrigger>
          <SelectPickerContent>
            <SelectPickerItem
              v-for="status in statuses"
              :key="status"
              :item-key="status"
              :label="status"
            />
          </SelectPickerContent>
        </SelectPicker>
      </Field>
    </form.Field>
    <Alert
      v-if="form.state.submitError"
      severity="danger"
      title="Product could not be saved"
      :description="form.state.submitError.message"
    />
    <div class="flex justify-end gap-2 border-t border-border pt-5">
      <Button
        type="button"
        variant="ghost"
        tone="neutral"
        :is-disabled="form.state.isSubmitting"
        @click="emit('cancel')"
        >Cancel</Button
      >
      <Button type="submit" :is-loading="form.state.isSubmitting">
        {{ editing ? "Save changes" : "Register product" }}
      </Button>
    </div>
  </form>
</template>

// engineering/codebase/wheelhouse.frontend-services/src/presentation/products/components/RegisterProductForm.tsx
import { z } from 'zod';

import { Button } from '@wow-two-beta/ui/presentation/actions';
import { Card } from '@wow-two-beta/ui/presentation/display';
import { Alert } from '@wow-two-beta/ui/presentation/feedback';
import { Field, Select, TextInput } from '@wow-two-beta/ui/presentation/forms';

import type { ProductOperations } from '@/application/products';
import { parseRepoInput, type Product, type ProductStatus } from '@/domain/products';
import { useAppForm } from '@/form';

const STATUS_OPTIONS = ['Draft', 'Active', 'Paused', 'Killed'] as const satisfies readonly ProductStatus[];

// Provider is implied GitHub on the wire (no backend field). GitLab/Bitbucket are listed but
// disabled — an unsupported provider can't be selected; pasting one of their URLs surfaces an
// inline message instead. The `value` doubles as the host the parser maps an unsupported URL to.
const PROVIDER_OPTIONS = [
  { value: 'github', label: 'GitHub', disabled: false },
  { value: 'gitlab', label: 'GitLab (soon)', disabled: true },
  { value: 'bitbucket', label: 'Bitbucket (soon)', disabled: true },
] as const;

/** Editable shape of the product form — provider is display-only glue (implied GitHub on the wire). */
interface ProductValues {
  slug: string;
  name: string;
  provider: string;
  repo: string;
  status: ProductStatus;
}

/** Whole-form validation for {@link ProductValues} — the repo rule reuses the parser so an unsupported host blocks submit with its message. */
const ProductSchema = z.object({
  slug: z.string().trim().min(1, 'Slug is required'),
  name: z.string().trim().min(1, 'Name is required'),
  provider: z.string(),
  repo: z.string().superRefine((value, ctx) => {
    const parsed = parseRepoInput(value);
    if (parsed.provider === null) ctx.addIssue({ code: 'custom', message: parsed.error });
  }),
  status: z.enum(STATUS_OPTIONS),
});

interface RegisterProductFormProps {
  /** When set, the form edits this product (slug locked); otherwise it creates a new one. */
  product?: Product | undefined;
  create: ProductOperations['create'];
  update: ProductOperations['update'];
  onSaved: () => void;
  onCancel: () => void;
}

/** Inline form to register a new product, or edit an existing one (slug is immutable on edit). */
export function RegisterProductForm({ product, create, update, onSaved, onCancel }: RegisterProductFormProps) {
  const isEdit = product !== undefined;

  const form = useAppForm<ProductValues>({
    defaultValues: {
      slug: product?.slug ?? '',
      name: product?.name ?? '',
      provider: 'github',
      repo: product?.repo ?? '',
      status: product?.status ?? 'Draft',
    },
    schema: ProductSchema,
    onSubmit: async (values) => {
      // Provider is implied GitHub — only `owner/repo` goes to the backend.
      if (isEdit) {
        await update(product.id, { name: values.name, repo: values.repo.trim(), status: values.status });
      } else {
        await create({ slug: values.slug.trim(), name: values.name, repo: values.repo.trim() });
      }
      onSaved();
    },
  });

  // Runs on every repo-input change (covers paste): a supported URL is stripped to owner/repo and
  // the field is rewritten; an unsupported host / unparseable value keeps what the user typed —
  // the schema re-runs the parser and its message blocks submit; a bare owner/repo is accepted as-is.
  function onRepoChange(value: string, setValue: (value: string) => void) {
    const result = parseRepoInput(value);
    setValue(result.provider === null ? value : result.repo);
  }

  return (
    <Card className="border border-border p-5">
      <form className="flex flex-col gap-4" onSubmit={(e) => void form.handleSubmit(e)}>
        <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
          <form.Field name="slug">
            {(f) => (
              <Field label="Slug" isDisabled={isEdit}>
                <TextInput value={f.value} onChange={(e) => f.setValue(e.target.value)} onBlur={f.onBlur} placeholder="my-product" />
              </Field>
            )}
          </form.Field>
          <form.Field name="name">
            {(f) => (
              <Field label="Name">
                <TextInput value={f.value} onChange={(e) => f.setValue(e.target.value)} onBlur={f.onBlur} placeholder="My Product" />
              </Field>
            )}
          </form.Field>
          <form.Field name="repo">
            {(f) => (
              // Full width when registering; beside Status when editing.
              <div className={isEdit ? undefined : 'sm:col-span-2'}>
              <Field label="Repo (owner/repo or URL)">
                <div className="flex items-stretch gap-2">
                  <form.Field name="provider">
                    {(prov) => (
                      // The Select root is full-width; a fixed box keeps the repo input its room.
                      <div className="w-32 shrink-0">
                      <Select value={prov.value} onValueChange={(opt) => prov.setValue(opt?.value ?? 'github')}>
                        <Select.Trigger className="w-full" aria-label="Repository provider">
                          <Select.Value />
                        </Select.Trigger>
                        <Select.Content>
                          {PROVIDER_OPTIONS.map((p) => (
                            <Select.Item key={p.value} itemKey={p.value} label={p.label} isDisabled={p.disabled} />
                          ))}
                        </Select.Content>
                      </Select>
                      </div>
                    )}
                  </form.Field>
                  <div className="min-w-0 flex-1">
                    <TextInput
                      value={f.value}
                      onChange={(e) => onRepoChange(e.target.value, f.setValue)}
                      onBlur={f.onBlur}
                      placeholder="octocat/hello-world"
                    />
                  </div>
                </div>
              </Field>
              </div>
            )}
          </form.Field>
          {isEdit && (
            <form.Field name="status">
              {(f) => (
                <Field label="Status">
                  <Select<ProductStatus> value={f.value} onValueChange={(opt) => f.setValue(opt?.value ?? f.value)}>
                    <Select.Trigger className="w-full">
                      <Select.Value />
                    </Select.Trigger>
                    <Select.Content>
                      {STATUS_OPTIONS.map((s) => (
                        <Select.Item key={s} itemKey={s} label={s} />
                      ))}
                    </Select.Content>
                  </Select>
                </Field>
              )}
            </form.Field>
          )}
        </div>

        <form.Subscribe selector={(s) => s.submitError}>
          {(error) =>
            error && <Alert severity="danger" title={`Could not ${isEdit ? 'save' : 'register'}`} description={error.message} />
          }
        </form.Subscribe>

        <div className="flex items-center justify-end gap-2">
          <Button type="button" variant="ghost" tone="neutral" onClick={onCancel}>
            Cancel
          </Button>
          <form.Subscribe selector={(s) => s.isSubmitting}>
            {(busy) => (
              <Button type="submit" variant="solid" tone="primary" isLoading={busy}>
                {isEdit ? 'Save changes' : 'Register product'}
              </Button>
            )}
          </form.Subscribe>
        </div>
      </form>
    </Card>
  );
}
