// engineering/codebase/wheelhouse.frontend-services/src/presentation/secrets/pages/SecretsPage.tsx
import { useEffect, useState } from 'react';
import { KeyRound } from 'lucide-react';
import { Badge, EmptyState, Tabs } from '@wow-two-beta/ui/presentation/display';
import { Select } from '@wow-two-beta/ui/presentation/forms';
import { useVaultHygiene, useVaults } from '@/application/secrets';
import { VaultStatus } from '@/domain/secrets';
import { LoadState, Panel } from '@/presentation/common/components';
import { NamespaceList } from '../components/NamespaceList';
import { SecretsTable } from '../components/SecretsTable';
import { TokensTable } from '../components/TokensTable';

const STATUS_VARIANT = { unsealed: 'success', sealed: 'warning', unreachable: 'danger' } as const;

const count = (amount: number, noun: string) => `${amount} ${noun}${amount === 1 ? '' : 's'}`;

/** Administers the code-owned vaults: namespaces, write-only secrets and product tokens. */
export function SecretsPage() {
  const vaults = useVaults();
  const [vault, setVault] = useState('');
  const [ns, setNs] = useState('');
  const selected = vaults.data?.find((item) => item.id === vault);
  const hygiene = useVaultHygiene(selected?.status === VaultStatus.Unsealed ? vault : '');
  const overdueSecrets = new Set(
    (hygiene.data?.overdueSecrets ?? []).filter((secret) => secret.namespace === ns).map((secret) => secret.key));
  const tokenFlags = new Map(
    (hygiene.data?.overdueTokens ?? []).filter((token) => token.namespace === ns).map((token) => [token.id, token.reason]));
  const dueCount = (hygiene.data?.overdueSecrets.length ?? 0) + (hygiene.data?.overdueTokens.length ?? 0);

  // ---- Default to the first vault once the catalog loads ----
  useEffect(() => {
    const first = vaults.data?.[0];
    if (!vault && first) setVault(first.id);
  }, [vaults.data, vault]);

  return (
    <LoadState loading={vaults.loading} error={vaults.error} empty={!vaults.data?.length}
      emptyTitle="No vaults configured" emptyDescription="Vaults are defined in reviewed code (fleet.py)."
      onRetry={() => void vaults.refetch()}>
      <Panel
        title={
          <span className="flex items-center gap-2">
            {selected?.name ?? 'Vault'}
            {selected && <Badge variant={STATUS_VARIANT[selected.status]}>{selected.status}</Badge>}
          </span>
        }
        description={
          dueCount > 0 && hygiene.data
            ? `Values are write-only. Due for rotation: ${count(hygiene.data.overdueSecrets.length, 'secret')} and ${count(hygiene.data.overdueTokens.length, 'token')}.`
            : 'Values are write-only: Wheelhouse sends them to the vault and shows only metadata.'
        }
        actions={(vaults.data?.length ?? 0) > 1 && (
          <Select<string> value={vault || null} onValueChange={(option) => { setVault(option?.value ?? ''); setNs(''); }}
            getOptionLabel={(key) => vaults.data?.find((item) => item.id === key)?.name ?? key}>
            <Select.Trigger size="sm" aria-label="Vault"><Select.Value placeholder="Select a vault" /></Select.Trigger>
            <Select.Content>
              {(vaults.data ?? []).map((item) => <Select.Item key={item.id} itemKey={item.id} label={item.name} />)}
            </Select.Content>
          </Select>
        )}
      >
        {selected && selected.status !== VaultStatus.Unsealed ? (
          <EmptyState size="sm" icon={<KeyRound size={24} />} title={`This vault is ${selected.status}`}
            description="Unseal it or restore connectivity from Wheelhouse before administering it." />
        ) : vault && (
          // The namespace rail runs edge to edge inside the card, divided from the namespace it opens.
          <div className="-m-5 grid min-h-96 lg:grid-cols-[16rem_minmax(0,1fr)]">
            <aside className="border-b border-border bg-muted/40 p-4 lg:rounded-bl-xl lg:border-r lg:border-b-0">
              <NamespaceList vault={vault} selected={ns} onSelect={setNs} />
            </aside>
            <section className="min-w-0 p-5">
              {ns ? (
                <Tabs key={ns} defaultValue="secrets" className="min-w-0">
                  <Tabs.List>
                    <Tabs.Tab value="secrets">Secrets</Tabs.Tab>
                    <Tabs.Tab value="tokens">Tokens</Tabs.Tab>
                  </Tabs.List>
                  <Tabs.Panel value="secrets" className="pt-4"><SecretsTable vault={vault} ns={ns} overdue={overdueSecrets} /></Tabs.Panel>
                  <Tabs.Panel value="tokens" className="pt-4"><TokensTable vault={vault} ns={ns} flags={tokenFlags} /></Tabs.Panel>
                </Tabs>
              ) : (
                <EmptyState size="sm" icon={<KeyRound size={24} />} title="Select a namespace"
                  description="Its write-only secrets and product tokens open here." />
              )}
            </section>
          </div>
        )}
      </Panel>
    </LoadState>
  );
}

// engineering/codebase/wheelhouse.frontend-services/src/presentation/secrets/pages/SecretsPage.vue
<script setup lang="ts">
import { computed, ref, watch } from "vue";
import { KeyRound, RefreshCw } from "lucide-vue-next";
import { Button } from "@wow-two-beta/ui-vue/presentation/actions";
import {
  Badge,
  EmptyState,
  TabsGroup,
  TabsGroupList,
  TabsGroupTab,
  TabsGroupPanel,
} from "@wow-two-beta/ui-vue/presentation/display";
import {
  Alert,
  SkeletonState,
} from "@wow-two-beta/ui-vue/presentation/feedback";
import {
  SelectPicker,
  SelectPickerTrigger,
  SelectPickerValue,
  SelectPickerContent,
  SelectPickerItem,
} from "@wow-two-beta/ui-vue/presentation/forms";
import { SecretKeys, useVaultHygiene, useVaults } from "@/application/secrets";
import { useInvalidate } from "@/bootstrap/query";
import { useRefresh } from "@/application/common";
import { VaultStatus } from "@/domain/secrets";
import LoadState from "@/presentation/common/components/LoadState.vue";
import Panel from "@/presentation/common/components/Panel.vue";
import PageActions from "@/presentation/common/components/PageActions.vue";
import NamespaceList from "../components/NamespaceList.vue";
import SecretsTable from "../components/SecretsTable.vue";
import TokensTable from "../components/TokensTable.vue";

/** Presents vault availability, namespace selection, write-only secrets, and token administration. */
defineOptions({ name: "SecretsPage" });
defineSlots<{}>();

/** @internal Maps live vault availability to its visible status. */
const VaultTone = {
  unsealed: "success",
  sealed: "warning",
  unreachable: "danger",
} as const;
const { data: vaults, loading, error } = useVaults();
const invalidate = useInvalidate();
const { refresh, refreshing } = useRefresh(() => invalidate(SecretKeys.vaults));
const vault = ref("");
const namespace = ref("");
const selected = computed(() =>
  vaults.value?.find((item) => item.id === vault.value),
);
const hygiene = useVaultHygiene(() =>
  selected.value?.status === VaultStatus.Unsealed ? vault.value : "",
);
const hygieneData = hygiene.data;
const hygieneError = hygiene.error;
const hygieneLoading = hygiene.loading;
/** The keys overdue for rotation in the selected namespace. */
const overdueSecrets = computed(
  () =>
    new Set(
      (hygieneData.value?.overdueSecrets ?? [])
        .filter((secret) => secret.namespace === namespace.value)
        .map((secret) => secret.key),
    ),
);
/** The token warnings scoped to the selected namespace. */
const tokenFlags = computed(
  () =>
    new Map(
      (hygieneData.value?.overdueTokens ?? [])
        .filter((token) => token.namespace === namespace.value)
        .map((token) => [token.id, token.reason]),
    ),
);
const dueCount = computed(
  () =>
    (hygieneData.value?.overdueSecrets.length ?? 0) +
    (hygieneData.value?.overdueTokens.length ?? 0),
);

/** Chooses an available vault when the catalog loads or removes the current vault. */
watch(
  vaults,
  (items) => {
    if (items && !items.some((item) => item.id === vault.value))
      vault.value = items[0]?.id ?? "";
  },
  { immediate: true },
);
/** Resets the namespace immediately when its owning vault changes. */
watch(
  vault,
  () => {
    namespace.value = "";
  },
  { flush: "sync" },
);

/** Changes the authoritative vault selection. */
function selectVault(value: unknown): void {
  vault.value = typeof value === "string" ? value : "";
}
</script>

<template>
  <PageActions>
    <Button
      variant="outline"
      tone="neutral"
      size="sm"
      :is-loading="refreshing"
      @click="refresh"
    >
      <template #leading><RefreshCw :size="14" /></template>Refresh
    </Button>
  </PageActions>
  <LoadState
    :loading="loading || refreshing"
    :error="error"
    :has-data="vaults !== undefined"
    :empty="!vaults?.length"
    empty-title="No vaults configured"
    empty-description="Configured vaults appear here when they are available."
    @retry="refresh"
  >
    <template #skeleton>
      <div class="min-h-96 space-y-5">
        <SkeletonState class="h-8 w-48" />
        <SkeletonState class="h-6 w-80 max-w-full" />
        <div class="grid gap-5 lg:grid-cols-[15rem_minmax(0,1fr)]">
          <SkeletonState class="h-64 w-full" />
          <SkeletonState class="h-64 w-full" />
        </div>
      </div>
    </template>
    <Panel
      :title="selected?.name ?? 'Vault'"
      description="Select a namespace to manage its write-only secrets and product access tokens."
    >
      <template #actions>
        <Badge v-if="selected" :variant="VaultTone[selected.status]">{{
          selected.status
        }}</Badge>
        <SelectPicker
          v-if="(vaults?.length ?? 0) > 1"
          :model-value="vault || null"
          :get-option-label="
            (id) => vaults?.find((item) => item.id === id)?.name ?? String(id)
          "
          @update:model-value="selectVault"
        >
          <SelectPickerTrigger size="sm" aria-label="Vault">
            <SelectPickerValue placeholder="Select a vault" />
          </SelectPickerTrigger>
          <SelectPickerContent>
            <SelectPickerItem
              v-for="item in vaults ?? []"
              :key="item.id"
              :item-key="item.id"
              :label="item.name"
            />
          </SelectPickerContent>
        </SelectPicker>
      </template>
      <EmptyState
        v-if="selected && selected.status !== VaultStatus.Unsealed"
        size="sm"
        :title="`This vault is ${selected.status}`"
        description="Unseal the vault or restore its connection to manage its namespaces."
      >
        <template #icon><KeyRound :size="24" /></template>
      </EmptyState>
      <div v-else-if="vault" :key="vault" class="flex flex-col gap-5">
        <Alert
          v-if="hygieneError"
          severity="warning"
          title="Rotation status unavailable"
          :description="hygieneError.message"
        >
          <template #actions>
            <Button
              size="sm"
              variant="ghost"
              tone="neutral"
              @click="hygiene.refetch()"
              >Retry</Button
            >
          </template>
        </Alert>
        <div
          v-else-if="hygieneData"
          class="flex flex-wrap items-center gap-2 text-xs text-muted-foreground"
        >
          <Badge :variant="dueCount > 0 ? 'warning' : 'success'">
            {{
              dueCount > 0
                ? `${dueCount} rotation issue${dueCount === 1 ? "" : "s"}`
                : "Rotation up to date"
            }}
          </Badge>
          <span
            >{{ hygieneData.secrets }} secrets · {{ hygieneData.tokens }} tokens
            across this vault</span
          >
        </div>
        <p
          v-else-if="hygieneLoading"
          class="text-xs text-muted-foreground"
          role="status"
        >
          Checking rotation status…
        </p>
        <div
          class="grid min-h-96 overflow-hidden rounded-2xl border border-border lg:grid-cols-[15rem_minmax(0,1fr)]"
        >
          <aside
            class="border-b border-border bg-muted/40 p-4 lg:border-b-0 lg:border-r"
          >
            <NamespaceList
              :vault="vault"
              :selected="namespace"
              @select="namespace = $event"
            />
          </aside>
          <section class="min-w-0 bg-card p-4 lg:p-5">
            <template v-if="namespace">
              <div class="mb-5 flex flex-wrap items-center gap-2">
                <KeyRound :size="16" class="text-primary" />
                <h2 class="break-all font-mono text-sm font-semibold">
                  {{ namespace }}
                </h2>
              </div>
              <TabsGroup
                :key="`${vault}/${namespace}`"
                default-value="secrets"
                class="min-w-0"
              >
                <TabsGroupList aria-label="Namespace administration">
                  <TabsGroupTab value="secrets">Secrets</TabsGroupTab>
                  <TabsGroupTab value="tokens">Tokens</TabsGroupTab>
                </TabsGroupList>
                <TabsGroupPanel value="secrets" class="pt-5">
                  <SecretsTable
                    :vault="vault"
                    :ns="namespace"
                    :overdue="overdueSecrets"
                  />
                </TabsGroupPanel>
                <TabsGroupPanel value="tokens" class="pt-5">
                  <TokensTable
                    :vault="vault"
                    :ns="namespace"
                    :flags="tokenFlags"
                  />
                </TabsGroupPanel>
              </TabsGroup>
            </template>
            <EmptyState
              v-else
              size="sm"
              title="Select a namespace"
              description="Its secrets and product tokens open here."
            >
              <template #icon><KeyRound :size="24" /></template>
            </EmptyState>
          </section>
        </div>
      </div>
    </Panel>
  </LoadState>
</template>
