// engineering/codebase/wheelhouse.frontend-services/src/bootstrap/AppLayout.tsx
import { useState, type ReactNode } from 'react';
import { useLocation } from 'react-router-dom';
import { Menu, Ship } from 'lucide-react';
import { Button } from '@wow-two-beta/ui/presentation/actions';
import { Badge, Heading, Text } from '@wow-two-beta/ui/presentation/display';
import { AppShell } from '@wow-two-beta/ui/presentation/layout';
import { useApiConnection } from '@/application/system';
import type { CurrentUser } from '@/domain/auth';
import { PageActionsOutlet, PageActionsProvider } from '@/presentation/common/components';
import { Sidebar, SidebarToggle, useColorScheme, useSidebarCollapsed } from '@/presentation/shell';
import { APP_ROUTES } from './routes';

/** Props for {@link AppLayout}. */
export interface AppLayoutProps {
  user: CurrentUser;
  onSignOut: () => void;
  children: ReactNode;
}

/** The signed-in frame: a full-height sidebar, and the routed page under its own header. */
export function AppLayout(props: AppLayoutProps) {
  const { connection, localRig } = useApiConnection();
  const location = useLocation();
  const [menuOpen, setMenuOpen] = useState(false);
  const { collapsed, toggle } = useSidebarCollapsed();
  const { scheme, setScheme } = useColorScheme();
  const current = APP_ROUTES.find((route) => route.path === location.pathname);
  const sidebarWidth = collapsed ? '68px' : '256px';
  return (
    <PageActionsProvider>
    <AppShell sidebarWidth={sidebarWidth} isSidebarOpen={menuOpen} onSidebarOpenChange={setMenuOpen}
      className="transition-[grid-template-columns] duration-200 ease-out motion-reduce:transition-none">
      {/* Small screens only: the sidebar becomes a drawer behind this bar. */}
      <AppShell.Header className="lg:hidden">
        <Button variant="ghost" tone="neutral" size="sm" aria-label="Open navigation"
          leadingSlot={<Menu size={18} />} onClick={() => setMenuOpen(true)} />
        <span className="flex size-7 items-center justify-center rounded-md bg-sidebar-accent text-sidebar-deep">
          <Ship size={16} />
        </span>
        <span className="font-semibold">Wheelhouse</span>
        {localRig && <Badge className="ml-auto whitespace-nowrap" variant="warning">Local rig</Badge>}
      </AppShell.Header>
      {/* Below lg the shell renders a padded drawer; the navy panel covers that padding edge to edge. */}
      <AppShell.Sidebar className="top-0 h-svh overflow-x-hidden border-r-0 bg-sidebar text-sidebar-foreground max-lg:-m-6 max-lg:h-[calc(100%+3rem)] max-lg:p-4">
        <Sidebar links={APP_ROUTES} activePath={current?.path} collapsed={collapsed}
          onNavigate={() => setMenuOpen(false)} localRig={localRig} user={props.user} connection={connection}
          scheme={scheme} onSchemeChange={setScheme} onSignOut={props.onSignOut} />
      </AppShell.Sidebar>
      <SidebarToggle collapsed={collapsed} width={sidebarWidth} onToggle={toggle} />
      <AppShell.Main className="min-w-0">
        <AppShell.Content className="p-4 sm:p-6 lg:px-10 lg:py-8">
          <div className="mx-auto flex max-w-6xl flex-col gap-6">
            {current && (
              <header className="flex flex-wrap items-end justify-between gap-x-6 gap-y-3">
                <div className="flex min-w-0 flex-col gap-1">
                  <Heading level={1} size="xl">{current.label}</Heading>
                  <Text color="muted">{current.description}</Text>
                </div>
                <PageActionsOutlet className="flex flex-wrap items-center gap-2 empty:hidden" />
              </header>
            )}
            {props.children}
          </div>
        </AppShell.Content>
      </AppShell.Main>
    </AppShell>
    </PageActionsProvider>
  );
}

// engineering/codebase/wheelhouse.frontend-services/apps/web/src/bootstrap/AppLayout.vue
<script lang="ts">
import type { CurrentUser } from '@/domain/auth';

/** Defines the authenticated workspace frame. */
export interface AppLayoutProps {
  readonly user: CurrentUser;
}
</script>
<script setup lang="ts">
import { computed, useTemplateRef, watch } from 'vue';
import { RouterLink, useRoute } from 'vue-router';
import { Badge } from '@wow-two-beta/ui-vue/presentation/display';
import { useApiConnection } from '@/application/system';
import { BrandWordmark, ProfileMenu, useColorScheme } from '@/presentation/shell';
import { AppPlaces } from './routes';

/** Combines the deployment desk's top navigation with a contextual studio workspace. */
defineOptions({ name: 'AppLayout' });
const props = defineProps<AppLayoutProps>();
const emit = defineEmits<{ signOut: [] }>();
defineSlots<{ default(): unknown }>();
const route = useRoute();
const system = useApiConnection();
const theme = useColorScheme();
const current = computed(() => AppPlaces.find((place) => place.path === route.path));
const consoleVersion = __APP_VERSION__;
/** A numbered build shows as `v0.3.4`; a local build shows `dev`. @internal */
const versionLabel = /^\d/.test(consoleVersion) ? `v${consoleVersion}` : consoleVersion;
const mainElement = useTemplateRef<HTMLElement>('main');

/** The main region is the scroll container, so a new page starts at its top. */
watch(
  () => route.path,
  () => mainElement.value?.scrollTo({ top: 0 }),
);
</script>
<template>
  <!-- The frame owns the viewport: the header spans the full window and only the main region scrolls, so no
       platform scrollbar ever cuts the header short. -->
  <div class="wh-ambient flex h-dvh flex-col overflow-hidden text-foreground">
    <a
      href="#main-content"
      class="sr-only focus:not-sr-only focus:fixed focus:left-4 focus:top-4 focus:z-50 focus:rounded-lg focus:bg-card focus:p-3"
      >Skip to content</a
    >
    <header class="wh-glass wh-glass-navigation relative z-30 shrink-0 border-b">
      <div class="mx-auto flex max-w-[1600px] flex-wrap items-center gap-x-7 px-4 sm:px-6 xl:px-8">
        <RouterLink
          :to="{ path: '/', query: route.query }"
          class="flex h-[72px] shrink-0 items-center gap-2.5"
          aria-label="Wheelhouse workspace"
        >
          <BrandWordmark :height="26" />
          <span
            class="rounded-md bg-muted px-1.5 py-0.5 font-mono text-[11px] font-medium text-muted-foreground"
            :title="`Console ${consoleVersion}`"
            >{{ versionLabel }}</span
          >
        </RouterLink>
        <nav
          aria-label="Primary navigation"
          class="order-3 -mx-4 flex w-[calc(100%+2rem)] shrink-0 gap-1 overflow-x-auto px-4 pb-2 md:order-none md:mx-0 md:w-auto md:shrink md:flex-1 md:p-0"
        >
          <RouterLink
            v-for="place in AppPlaces"
            :key="place.path"
            :to="{ path: place.path, query: route.query }"
            :aria-current="route.path === place.path ? 'page' : undefined"
            class="whitespace-nowrap rounded-lg px-3 py-2 text-sm font-medium transition-colors focus-visible:outline-2 focus-visible:outline-ring"
            :class="
              route.path === place.path
                ? 'bg-primary-soft text-primary-soft-foreground'
                : 'text-muted-foreground hover:bg-muted hover:text-foreground'
            "
            >{{ place.label }}</RouterLink
          >
        </nav>
        <div class="ml-auto flex items-center gap-3">
          <Badge v-if="system.localRig.value" variant="warning" title="Deployments go to the local server"
            >Local server</Badge
          >
          <ProfileMenu
            :user="props.user"
            :connection="system.connection.value"
            :api-version="system.version.value"
            :scheme="theme.scheme.value"
            @scheme="theme.setScheme"
            @sign-out="emit('signOut')"
          />
        </div>
      </div>
    </header>
    <main
      id="main-content"
      ref="main"
      tabindex="-1"
      class="min-h-0 flex-1 overflow-y-auto [scrollbar-gutter:stable] focus:outline-none"
    >
      <div class="mx-auto max-w-[1600px] px-4 py-6 sm:px-6 lg:py-8 xl:px-8">
        <header class="mb-6 flex flex-wrap items-end justify-between gap-4">
          <div>
            <h1 class="text-2xl font-semibold tracking-tight">{{ current?.label }}</h1>
            <p class="mt-1 text-sm text-muted-foreground">{{ current?.description }}</p>
          </div>
          <div id="page-actions" class="flex flex-wrap items-center gap-2 empty:hidden" />
        </header>
        <slot />
      </div>
    </main>
  </div>
</template>
